// Code generated by ncraft. DO NOT EDIT.
// Rerunning ncraft will overwrite this file.
// Version: 0.1.0
// Version Date:

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/tracing/opentracing"
	grpctransport "github.com/go-kit/kit/transport/grpc"
	stdopentracing "github.com/opentracing/opentracing-go"

	"github.com/mojo-lang/mojo/go/pkg/mojo/core"
	"github.com/ncraft-io/tilestream/go/pkg/tilestream"

	// this service api
	pb "github.com/ncraft-io/tilestream/go/pkg/tilestream/v1"
)

var (
	_ = tilestream.Tile{}
	_ = core.Null{}
	_ = tilestream.TileInfo{}
	_ = tilestream.Layer{}
	_ = core.Ordering{}
	_ = core.FieldMask{}
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TilestreamServer.
func MakeGRPCServer(endpoints Endpoints, tracer stdopentracing.Tracer, logger log.Logger) pb.TilestreamServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
		grpctransport.ServerErrorLogger(logger),
	}

	addTracerOption := func(methodName string) []grpctransport.ServerOption {
		if tracer != nil {
			return append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, methodName, logger)))
		}
		return serverOptions
	}

	return &grpcServer{
		// Tilestream

		createTile: grpctransport.NewServer(
			endpoints.CreateTileEndpoint,
			DecodeGRPCCreateTileRequest,
			EncodeGRPCCreateTileResponse,
			addTracerOption("create_tile")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "create_tile", logger)))...,
		),
		batchCreateTiles: grpctransport.NewServer(
			endpoints.BatchCreateTilesEndpoint,
			DecodeGRPCBatchCreateTilesRequest,
			EncodeGRPCBatchCreateTilesResponse,
			addTracerOption("batch_create_tiles")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "batch_create_tiles", logger)))...,
		),
		createTiles: grpctransport.NewServer(
			endpoints.CreateTilesEndpoint,
			DecodeGRPCCreateTilesRequest,
			EncodeGRPCCreateTilesResponse,
			addTracerOption("create_tiles")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "create_tiles", logger)))...,
		),
		getTile: grpctransport.NewServer(
			endpoints.GetTileEndpoint,
			DecodeGRPCGetTileRequest,
			EncodeGRPCGetTileResponse,
			addTracerOption("get_tile")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "get_tile", logger)))...,
		),
		getTileInfo: grpctransport.NewServer(
			endpoints.GetTileInfoEndpoint,
			DecodeGRPCGetTileInfoRequest,
			EncodeGRPCGetTileInfoResponse,
			addTracerOption("get_tile_info")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "get_tile_info", logger)))...,
		),
		updateTile: grpctransport.NewServer(
			endpoints.UpdateTileEndpoint,
			DecodeGRPCUpdateTileRequest,
			EncodeGRPCUpdateTileResponse,
			addTracerOption("update_tile")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "update_tile", logger)))...,
		),
		updateTileInfo: grpctransport.NewServer(
			endpoints.UpdateTileInfoEndpoint,
			DecodeGRPCUpdateTileInfoRequest,
			EncodeGRPCUpdateTileInfoResponse,
			addTracerOption("update_tile_info")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "update_tile_info", logger)))...,
		),
		createLayer: grpctransport.NewServer(
			endpoints.CreateLayerEndpoint,
			DecodeGRPCCreateLayerRequest,
			EncodeGRPCCreateLayerResponse,
			addTracerOption("create_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "create_layer", logger)))...,
		),
		batchCreateLayer: grpctransport.NewServer(
			endpoints.BatchCreateLayerEndpoint,
			DecodeGRPCBatchCreateLayerRequest,
			EncodeGRPCBatchCreateLayerResponse,
			addTracerOption("batch_create_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "batch_create_layer", logger)))...,
		),
		updateLayer: grpctransport.NewServer(
			endpoints.UpdateLayerEndpoint,
			DecodeGRPCUpdateLayerRequest,
			EncodeGRPCUpdateLayerResponse,
			addTracerOption("update_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "update_layer", logger)))...,
		),
		batchUpdateLayer: grpctransport.NewServer(
			endpoints.BatchUpdateLayerEndpoint,
			DecodeGRPCBatchUpdateLayerRequest,
			EncodeGRPCBatchUpdateLayerResponse,
			addTracerOption("batch_update_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "batch_update_layer", logger)))...,
		),
		deleteLayer: grpctransport.NewServer(
			endpoints.DeleteLayerEndpoint,
			DecodeGRPCDeleteLayerRequest,
			EncodeGRPCDeleteLayerResponse,
			addTracerOption("delete_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "delete_layer", logger)))...,
		),
		getLayer: grpctransport.NewServer(
			endpoints.GetLayerEndpoint,
			DecodeGRPCGetLayerRequest,
			EncodeGRPCGetLayerResponse,
			addTracerOption("get_layer")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "get_layer", logger)))...,
		),
		batchGetLayers: grpctransport.NewServer(
			endpoints.BatchGetLayersEndpoint,
			DecodeGRPCBatchGetLayersRequest,
			EncodeGRPCBatchGetLayersResponse,
			addTracerOption("batch_get_layers")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "batch_get_layers", logger)))...,
		),
		listLayers: grpctransport.NewServer(
			endpoints.ListLayersEndpoint,
			DecodeGRPCListLayersRequest,
			EncodeGRPCListLayersResponse,
			addTracerOption("list_layers")...,
		//append(serverOptions, grpctransport.ServerBefore(opentracing.GRPCToContext(tracer, "list_layers", logger)))...,
		),
	}
}

// grpcServer implements the TilestreamServer interface
type grpcServer struct {
	pb.UnimplementedTilestreamServer

	createTile       grpctransport.Handler
	batchCreateTiles grpctransport.Handler
	createTiles      grpctransport.Handler
	getTile          grpctransport.Handler
	getTileInfo      grpctransport.Handler
	updateTile       grpctransport.Handler
	updateTileInfo   grpctransport.Handler
	createLayer      grpctransport.Handler
	batchCreateLayer grpctransport.Handler
	updateLayer      grpctransport.Handler
	batchUpdateLayer grpctransport.Handler
	deleteLayer      grpctransport.Handler
	getLayer         grpctransport.Handler
	batchGetLayers   grpctransport.Handler
	listLayers       grpctransport.Handler
}

// Methods for grpcServer to implement TilestreamServer interface

func (s *grpcServer) CreateTile(ctx context.Context, req *pb.CreateTileRequest) (*tilestream.Tile, error) {
	_, rep, err := s.createTile.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*tilestream.Tile), nil
}

func (s *grpcServer) BatchCreateTiles(ctx context.Context, req *pb.BatchCreateTilesRequest) (*core.Null, error) {
	_, rep, err := s.batchCreateTiles.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) CreateTiles(ctx context.Context, req *pb.CreateTilesRequest) (*core.Null, error) {
	_, rep, err := s.createTiles.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) GetTile(ctx context.Context, req *pb.GetTileRequest) (*tilestream.Tile, error) {
	_, rep, err := s.getTile.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*tilestream.Tile), nil
}

func (s *grpcServer) GetTileInfo(ctx context.Context, req *pb.GetTileInfoRequest) (*tilestream.TileInfo, error) {
	_, rep, err := s.getTileInfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*tilestream.TileInfo), nil
}

func (s *grpcServer) UpdateTile(ctx context.Context, req *pb.UpdateTileRequest) (*core.Null, error) {
	_, rep, err := s.updateTile.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) UpdateTileInfo(ctx context.Context, req *pb.UpdateTileInfoRequest) (*core.Null, error) {
	_, rep, err := s.updateTileInfo.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) CreateLayer(ctx context.Context, req *pb.CreateLayerRequest) (*tilestream.Layer, error) {
	_, rep, err := s.createLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*tilestream.Layer), nil
}

func (s *grpcServer) BatchCreateLayer(ctx context.Context, req *pb.BatchCreateLayerRequest) (*pb.BatchCreateLayerResponse, error) {
	_, rep, err := s.batchCreateLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.BatchCreateLayerResponse), nil
}

func (s *grpcServer) UpdateLayer(ctx context.Context, req *pb.UpdateLayerRequest) (*core.Null, error) {
	_, rep, err := s.updateLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) BatchUpdateLayer(ctx context.Context, req *pb.BatchUpdateLayerRequest) (*core.Null, error) {
	_, rep, err := s.batchUpdateLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) DeleteLayer(ctx context.Context, req *pb.DeleteLayerRequest) (*core.Null, error) {
	_, rep, err := s.deleteLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*core.Null), nil
}

func (s *grpcServer) GetLayer(ctx context.Context, req *pb.GetLayerRequest) (*tilestream.Layer, error) {
	_, rep, err := s.getLayer.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*tilestream.Layer), nil
}

func (s *grpcServer) BatchGetLayers(ctx context.Context, req *pb.BatchGetLayersRequest) (*pb.BatchGetLayersResponse, error) {
	_, rep, err := s.batchGetLayers.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.BatchGetLayersResponse), nil
}

func (s *grpcServer) ListLayers(ctx context.Context, req *pb.ListLayersRequest) (*pb.ListLayersResponse, error) {
	_, rep, err := s.listLayers.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListLayersResponse), nil
}

// Server Decode

// DecodeGRPCCreateTileRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC CreateTile request to a user-domain CreateTile request. Primarily useful in a server.
func DecodeGRPCCreateTileRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CreateTileRequest)
	return req, nil
}

// DecodeGRPCBatchCreateTilesRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC BatchCreateTiles request to a user-domain BatchCreateTiles request. Primarily useful in a server.
func DecodeGRPCBatchCreateTilesRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.BatchCreateTilesRequest)
	return req, nil
}

// DecodeGRPCCreateTilesRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC CreateTiles request to a user-domain CreateTiles request. Primarily useful in a server.
func DecodeGRPCCreateTilesRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CreateTilesRequest)
	return req, nil
}

// DecodeGRPCGetTileRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetTile request to a user-domain GetTile request. Primarily useful in a server.
func DecodeGRPCGetTileRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetTileRequest)
	return req, nil
}

// DecodeGRPCGetTileInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetTileInfo request to a user-domain GetTileInfo request. Primarily useful in a server.
func DecodeGRPCGetTileInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetTileInfoRequest)
	return req, nil
}

// DecodeGRPCUpdateTileRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC UpdateTile request to a user-domain UpdateTile request. Primarily useful in a server.
func DecodeGRPCUpdateTileRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UpdateTileRequest)
	return req, nil
}

// DecodeGRPCUpdateTileInfoRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC UpdateTileInfo request to a user-domain UpdateTileInfo request. Primarily useful in a server.
func DecodeGRPCUpdateTileInfoRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UpdateTileInfoRequest)
	return req, nil
}

// DecodeGRPCCreateLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC CreateLayer request to a user-domain CreateLayer request. Primarily useful in a server.
func DecodeGRPCCreateLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.CreateLayerRequest)
	return req, nil
}

// DecodeGRPCBatchCreateLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC BatchCreateLayer request to a user-domain BatchCreateLayer request. Primarily useful in a server.
func DecodeGRPCBatchCreateLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.BatchCreateLayerRequest)
	return req, nil
}

// DecodeGRPCUpdateLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC UpdateLayer request to a user-domain UpdateLayer request. Primarily useful in a server.
func DecodeGRPCUpdateLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.UpdateLayerRequest)
	return req, nil
}

// DecodeGRPCBatchUpdateLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC BatchUpdateLayer request to a user-domain BatchUpdateLayer request. Primarily useful in a server.
func DecodeGRPCBatchUpdateLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.BatchUpdateLayerRequest)
	return req, nil
}

// DecodeGRPCDeleteLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC DeleteLayer request to a user-domain DeleteLayer request. Primarily useful in a server.
func DecodeGRPCDeleteLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.DeleteLayerRequest)
	return req, nil
}

// DecodeGRPCGetLayerRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetLayer request to a user-domain GetLayer request. Primarily useful in a server.
func DecodeGRPCGetLayerRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetLayerRequest)
	return req, nil
}

// DecodeGRPCBatchGetLayersRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC BatchGetLayers request to a user-domain BatchGetLayers request. Primarily useful in a server.
func DecodeGRPCBatchGetLayersRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.BatchGetLayersRequest)
	return req, nil
}

// DecodeGRPCListLayersRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ListLayers request to a user-domain ListLayers request. Primarily useful in a server.
func DecodeGRPCListLayersRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListLayersRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCCreateTileResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain CreateTile response to a gRPC CreateTile reply. Primarily useful in a server.
func EncodeGRPCCreateTileResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*tilestream.Tile)
	return resp, nil
}

// EncodeGRPCBatchCreateTilesResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain BatchCreateTiles response to a gRPC BatchCreateTiles reply. Primarily useful in a server.
func EncodeGRPCBatchCreateTilesResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCCreateTilesResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain CreateTiles response to a gRPC CreateTiles reply. Primarily useful in a server.
func EncodeGRPCCreateTilesResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCGetTileResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetTile response to a gRPC GetTile reply. Primarily useful in a server.
func EncodeGRPCGetTileResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*tilestream.Tile)
	return resp, nil
}

// EncodeGRPCGetTileInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetTileInfo response to a gRPC GetTileInfo reply. Primarily useful in a server.
func EncodeGRPCGetTileInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*tilestream.TileInfo)
	return resp, nil
}

// EncodeGRPCUpdateTileResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain UpdateTile response to a gRPC UpdateTile reply. Primarily useful in a server.
func EncodeGRPCUpdateTileResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCUpdateTileInfoResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain UpdateTileInfo response to a gRPC UpdateTileInfo reply. Primarily useful in a server.
func EncodeGRPCUpdateTileInfoResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCCreateLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain CreateLayer response to a gRPC CreateLayer reply. Primarily useful in a server.
func EncodeGRPCCreateLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*tilestream.Layer)
	return resp, nil
}

// EncodeGRPCBatchCreateLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain BatchCreateLayer response to a gRPC BatchCreateLayer reply. Primarily useful in a server.
func EncodeGRPCBatchCreateLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.BatchCreateLayerResponse)
	return resp, nil
}

// EncodeGRPCUpdateLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain UpdateLayer response to a gRPC UpdateLayer reply. Primarily useful in a server.
func EncodeGRPCUpdateLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCBatchUpdateLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain BatchUpdateLayer response to a gRPC BatchUpdateLayer reply. Primarily useful in a server.
func EncodeGRPCBatchUpdateLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCDeleteLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain DeleteLayer response to a gRPC DeleteLayer reply. Primarily useful in a server.
func EncodeGRPCDeleteLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*core.Null)
	return resp, nil
}

// EncodeGRPCGetLayerResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetLayer response to a gRPC GetLayer reply. Primarily useful in a server.
func EncodeGRPCGetLayerResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*tilestream.Layer)
	return resp, nil
}

// EncodeGRPCBatchGetLayersResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain BatchGetLayers response to a gRPC BatchGetLayers reply. Primarily useful in a server.
func EncodeGRPCBatchGetLayersResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.BatchGetLayersResponse)
	return resp, nil
}

// EncodeGRPCListLayersResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ListLayers response to a gRPC ListLayers reply. Primarily useful in a server.
func EncodeGRPCListLayersResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListLayersResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
