// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.BatchCreateLayerRequest}
 */
public final class BatchCreateLayerRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.BatchCreateLayerRequest)
    BatchCreateLayerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      BatchCreateLayerRequest.class.getName());
  }
  // Use BatchCreateLayerRequest.newBuilder() to construct.
  private BatchCreateLayerRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchCreateLayerRequest() {
    layers_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchCreateLayerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.BatchCreateLayerRequest.class, io.ncraft.tilestream.v1.BatchCreateLayerRequest.Builder.class);
  }

  public static final int LAYERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.ncraft.tilestream.Layer> layers_;
  /**
   * <code>repeated .tilestream.Layer layers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.ncraft.tilestream.Layer> getLayersList() {
    return layers_;
  }
  /**
   * <code>repeated .tilestream.Layer layers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.ncraft.tilestream.LayerOrBuilder> 
      getLayersOrBuilderList() {
    return layers_;
  }
  /**
   * <code>repeated .tilestream.Layer layers = 2;</code>
   */
  @java.lang.Override
  public int getLayersCount() {
    return layers_.size();
  }
  /**
   * <code>repeated .tilestream.Layer layers = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.Layer getLayers(int index) {
    return layers_.get(index);
  }
  /**
   * <code>repeated .tilestream.Layer layers = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.LayerOrBuilder getLayersOrBuilder(
      int index) {
    return layers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < layers_.size(); i++) {
      output.writeMessage(2, layers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < layers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, layers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.BatchCreateLayerRequest)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.BatchCreateLayerRequest other = (io.ncraft.tilestream.v1.BatchCreateLayerRequest) obj;

    if (!getLayersList()
        .equals(other.getLayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLayersCount() > 0) {
      hash = (37 * hash) + LAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getLayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.BatchCreateLayerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.BatchCreateLayerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.BatchCreateLayerRequest)
      io.ncraft.tilestream.v1.BatchCreateLayerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchCreateLayerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.BatchCreateLayerRequest.class, io.ncraft.tilestream.v1.BatchCreateLayerRequest.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.BatchCreateLayerRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (layersBuilder_ == null) {
        layers_ = java.util.Collections.emptyList();
      } else {
        layers_ = null;
        layersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchCreateLayerRequest getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.BatchCreateLayerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchCreateLayerRequest build() {
      io.ncraft.tilestream.v1.BatchCreateLayerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchCreateLayerRequest buildPartial() {
      io.ncraft.tilestream.v1.BatchCreateLayerRequest result = new io.ncraft.tilestream.v1.BatchCreateLayerRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.ncraft.tilestream.v1.BatchCreateLayerRequest result) {
      if (layersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          layers_ = java.util.Collections.unmodifiableList(layers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.layers_ = layers_;
      } else {
        result.layers_ = layersBuilder_.build();
      }
    }

    private void buildPartial0(io.ncraft.tilestream.v1.BatchCreateLayerRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.BatchCreateLayerRequest) {
        return mergeFrom((io.ncraft.tilestream.v1.BatchCreateLayerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.BatchCreateLayerRequest other) {
      if (other == io.ncraft.tilestream.v1.BatchCreateLayerRequest.getDefaultInstance()) return this;
      if (layersBuilder_ == null) {
        if (!other.layers_.isEmpty()) {
          if (layers_.isEmpty()) {
            layers_ = other.layers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLayersIsMutable();
            layers_.addAll(other.layers_);
          }
          onChanged();
        }
      } else {
        if (!other.layers_.isEmpty()) {
          if (layersBuilder_.isEmpty()) {
            layersBuilder_.dispose();
            layersBuilder_ = null;
            layers_ = other.layers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            layersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLayersFieldBuilder() : null;
          } else {
            layersBuilder_.addAllMessages(other.layers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              io.ncraft.tilestream.Layer m =
                  input.readMessage(
                      io.ncraft.tilestream.Layer.parser(),
                      extensionRegistry);
              if (layersBuilder_ == null) {
                ensureLayersIsMutable();
                layers_.add(m);
              } else {
                layersBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.ncraft.tilestream.Layer> layers_ =
      java.util.Collections.emptyList();
    private void ensureLayersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        layers_ = new java.util.ArrayList<io.ncraft.tilestream.Layer>(layers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder> layersBuilder_;

    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public java.util.List<io.ncraft.tilestream.Layer> getLayersList() {
      if (layersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(layers_);
      } else {
        return layersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public int getLayersCount() {
      if (layersBuilder_ == null) {
        return layers_.size();
      } else {
        return layersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public io.ncraft.tilestream.Layer getLayers(int index) {
      if (layersBuilder_ == null) {
        return layers_.get(index);
      } else {
        return layersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder setLayers(
        int index, io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.set(index, value);
        onChanged();
      } else {
        layersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder setLayers(
        int index, io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.set(index, builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder addLayers(io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.add(value);
        onChanged();
      } else {
        layersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder addLayers(
        int index, io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.add(index, value);
        onChanged();
      } else {
        layersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder addLayers(
        io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.add(builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder addLayers(
        int index, io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.add(index, builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder addAllLayers(
        java.lang.Iterable<? extends io.ncraft.tilestream.Layer> values) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, layers_);
        onChanged();
      } else {
        layersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder clearLayers() {
      if (layersBuilder_ == null) {
        layers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        layersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public Builder removeLayers(int index) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.remove(index);
        onChanged();
      } else {
        layersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public io.ncraft.tilestream.Layer.Builder getLayersBuilder(
        int index) {
      return getLayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public io.ncraft.tilestream.LayerOrBuilder getLayersOrBuilder(
        int index) {
      if (layersBuilder_ == null) {
        return layers_.get(index);  } else {
        return layersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public java.util.List<? extends io.ncraft.tilestream.LayerOrBuilder> 
         getLayersOrBuilderList() {
      if (layersBuilder_ != null) {
        return layersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(layers_);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public io.ncraft.tilestream.Layer.Builder addLayersBuilder() {
      return getLayersFieldBuilder().addBuilder(
          io.ncraft.tilestream.Layer.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public io.ncraft.tilestream.Layer.Builder addLayersBuilder(
        int index) {
      return getLayersFieldBuilder().addBuilder(
          index, io.ncraft.tilestream.Layer.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Layer layers = 2;</code>
     */
    public java.util.List<io.ncraft.tilestream.Layer.Builder> 
         getLayersBuilderList() {
      return getLayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder> 
        getLayersFieldBuilder() {
      if (layersBuilder_ == null) {
        layersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder>(
                layers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        layers_ = null;
      }
      return layersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.v1.BatchCreateLayerRequest)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.BatchCreateLayerRequest)
  private static final io.ncraft.tilestream.v1.BatchCreateLayerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.BatchCreateLayerRequest();
  }

  public static io.ncraft.tilestream.v1.BatchCreateLayerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchCreateLayerRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchCreateLayerRequest>() {
    @java.lang.Override
    public BatchCreateLayerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchCreateLayerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchCreateLayerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.BatchCreateLayerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

