// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.BatchGetLayersRequest}
 */
public final class BatchGetLayersRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.BatchGetLayersRequest)
    BatchGetLayersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      BatchGetLayersRequest.class.getName());
  }
  // Use BatchGetLayersRequest.newBuilder() to construct.
  private BatchGetLayersRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchGetLayersRequest() {
    layers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchGetLayersRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchGetLayersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.BatchGetLayersRequest.class, io.ncraft.tilestream.v1.BatchGetLayersRequest.Builder.class);
  }

  public static final int LAYERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList layers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string layers = 1;</code>
   * @return A list containing the layers.
   */
  public com.google.protobuf.ProtocolStringList
      getLayersList() {
    return layers_;
  }
  /**
   * <code>repeated string layers = 1;</code>
   * @return The count of layers.
   */
  public int getLayersCount() {
    return layers_.size();
  }
  /**
   * <code>repeated string layers = 1;</code>
   * @param index The index of the element to return.
   * @return The layers at the given index.
   */
  public java.lang.String getLayers(int index) {
    return layers_.get(index);
  }
  /**
   * <code>repeated string layers = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the layers at the given index.
   */
  public com.google.protobuf.ByteString
      getLayersBytes(int index) {
    return layers_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < layers_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, layers_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < layers_.size(); i++) {
        dataSize += computeStringSizeNoTag(layers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLayersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.BatchGetLayersRequest)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.BatchGetLayersRequest other = (io.ncraft.tilestream.v1.BatchGetLayersRequest) obj;

    if (!getLayersList()
        .equals(other.getLayersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLayersCount() > 0) {
      hash = (37 * hash) + LAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getLayersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.BatchGetLayersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.BatchGetLayersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.BatchGetLayersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.BatchGetLayersRequest)
      io.ncraft.tilestream.v1.BatchGetLayersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchGetLayersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchGetLayersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.BatchGetLayersRequest.class, io.ncraft.tilestream.v1.BatchGetLayersRequest.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.BatchGetLayersRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      layers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_BatchGetLayersRequest_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchGetLayersRequest getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.BatchGetLayersRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchGetLayersRequest build() {
      io.ncraft.tilestream.v1.BatchGetLayersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.BatchGetLayersRequest buildPartial() {
      io.ncraft.tilestream.v1.BatchGetLayersRequest result = new io.ncraft.tilestream.v1.BatchGetLayersRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.ncraft.tilestream.v1.BatchGetLayersRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        layers_.makeImmutable();
        result.layers_ = layers_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.BatchGetLayersRequest) {
        return mergeFrom((io.ncraft.tilestream.v1.BatchGetLayersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.BatchGetLayersRequest other) {
      if (other == io.ncraft.tilestream.v1.BatchGetLayersRequest.getDefaultInstance()) return this;
      if (!other.layers_.isEmpty()) {
        if (layers_.isEmpty()) {
          layers_ = other.layers_;
          bitField0_ |= 0x00000001;
        } else {
          ensureLayersIsMutable();
          layers_.addAll(other.layers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLayersIsMutable();
              layers_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList layers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLayersIsMutable() {
      if (!layers_.isModifiable()) {
        layers_ = new com.google.protobuf.LazyStringArrayList(layers_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @return A list containing the layers.
     */
    public com.google.protobuf.ProtocolStringList
        getLayersList() {
      layers_.makeImmutable();
      return layers_;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @return The count of layers.
     */
    public int getLayersCount() {
      return layers_.size();
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param index The index of the element to return.
     * @return The layers at the given index.
     */
    public java.lang.String getLayers(int index) {
      return layers_.get(index);
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the layers at the given index.
     */
    public com.google.protobuf.ByteString
        getLayersBytes(int index) {
      return layers_.getByteString(index);
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param index The index to set the value at.
     * @param value The layers to set.
     * @return This builder for chaining.
     */
    public Builder setLayers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLayersIsMutable();
      layers_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param value The layers to add.
     * @return This builder for chaining.
     */
    public Builder addLayers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLayersIsMutable();
      layers_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param values The layers to add.
     * @return This builder for chaining.
     */
    public Builder addAllLayers(
        java.lang.Iterable<java.lang.String> values) {
      ensureLayersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, layers_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLayers() {
      layers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string layers = 1;</code>
     * @param value The bytes of the layers to add.
     * @return This builder for chaining.
     */
    public Builder addLayersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLayersIsMutable();
      layers_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.v1.BatchGetLayersRequest)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.BatchGetLayersRequest)
  private static final io.ncraft.tilestream.v1.BatchGetLayersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.BatchGetLayersRequest();
  }

  public static io.ncraft.tilestream.v1.BatchGetLayersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchGetLayersRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchGetLayersRequest>() {
    @java.lang.Override
    public BatchGetLayersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchGetLayersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchGetLayersRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.BatchGetLayersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

