// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/v1/tilestream.proto

package io.ncraft.tilestream.v1;

public interface CreateLayerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.CreateLayerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tilestream.Layer layer = 1;</code>
   * @return Whether the layer field is set.
   */
  boolean hasLayer();
  /**
   * <code>.tilestream.Layer layer = 1;</code>
   * @return The layer.
   */
  io.ncraft.tilestream.Layer getLayer();
  /**
   * <code>.tilestream.Layer layer = 1;</code>
   */
  io.ncraft.tilestream.LayerOrBuilder getLayerOrBuilder();
}
