// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.CreateTilesRequest}
 */
public final class CreateTilesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.CreateTilesRequest)
    CreateTilesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      CreateTilesRequest.class.getName());
  }
  // Use CreateTilesRequest.newBuilder() to construct.
  private CreateTilesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateTilesRequest() {
    layer_ = "";
    tiles_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_CreateTilesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.CreateTilesRequest.class, io.ncraft.tilestream.v1.CreateTilesRequest.Builder.class);
  }

  public static final int LAYER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object layer_ = "";
  /**
   * <code>string layer = 1;</code>
   * @return The layer.
   */
  @java.lang.Override
  public java.lang.String getLayer() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      layer_ = s;
      return s;
    }
  }
  /**
   * <code>string layer = 1;</code>
   * @return The bytes for layer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLayerBytes() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      layer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TILES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.ncraft.tilestream.Tile> tiles_;
  /**
   * <code>repeated .tilestream.Tile tiles = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.ncraft.tilestream.Tile> getTilesList() {
    return tiles_;
  }
  /**
   * <code>repeated .tilestream.Tile tiles = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.ncraft.tilestream.TileOrBuilder> 
      getTilesOrBuilderList() {
    return tiles_;
  }
  /**
   * <code>repeated .tilestream.Tile tiles = 2;</code>
   */
  @java.lang.Override
  public int getTilesCount() {
    return tiles_.size();
  }
  /**
   * <code>repeated .tilestream.Tile tiles = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.Tile getTiles(int index) {
    return tiles_.get(index);
  }
  /**
   * <code>repeated .tilestream.Tile tiles = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.TileOrBuilder getTilesOrBuilder(
      int index) {
    return tiles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layer_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, layer_);
    }
    for (int i = 0; i < tiles_.size(); i++) {
      output.writeMessage(2, tiles_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layer_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, layer_);
    }
    for (int i = 0; i < tiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, tiles_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.CreateTilesRequest)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.CreateTilesRequest other = (io.ncraft.tilestream.v1.CreateTilesRequest) obj;

    if (!getLayer()
        .equals(other.getLayer())) return false;
    if (!getTilesList()
        .equals(other.getTilesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAYER_FIELD_NUMBER;
    hash = (53 * hash) + getLayer().hashCode();
    if (getTilesCount() > 0) {
      hash = (37 * hash) + TILES_FIELD_NUMBER;
      hash = (53 * hash) + getTilesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.v1.CreateTilesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.v1.CreateTilesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.CreateTilesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.CreateTilesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.CreateTilesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.CreateTilesRequest)
      io.ncraft.tilestream.v1.CreateTilesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_CreateTilesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.CreateTilesRequest.class, io.ncraft.tilestream.v1.CreateTilesRequest.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.CreateTilesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      layer_ = "";
      if (tilesBuilder_ == null) {
        tiles_ = java.util.Collections.emptyList();
      } else {
        tiles_ = null;
        tilesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_CreateTilesRequest_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.CreateTilesRequest getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.CreateTilesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.CreateTilesRequest build() {
      io.ncraft.tilestream.v1.CreateTilesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.CreateTilesRequest buildPartial() {
      io.ncraft.tilestream.v1.CreateTilesRequest result = new io.ncraft.tilestream.v1.CreateTilesRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.ncraft.tilestream.v1.CreateTilesRequest result) {
      if (tilesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          tiles_ = java.util.Collections.unmodifiableList(tiles_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tiles_ = tiles_;
      } else {
        result.tiles_ = tilesBuilder_.build();
      }
    }

    private void buildPartial0(io.ncraft.tilestream.v1.CreateTilesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.layer_ = layer_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.CreateTilesRequest) {
        return mergeFrom((io.ncraft.tilestream.v1.CreateTilesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.CreateTilesRequest other) {
      if (other == io.ncraft.tilestream.v1.CreateTilesRequest.getDefaultInstance()) return this;
      if (!other.getLayer().isEmpty()) {
        layer_ = other.layer_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (tilesBuilder_ == null) {
        if (!other.tiles_.isEmpty()) {
          if (tiles_.isEmpty()) {
            tiles_ = other.tiles_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTilesIsMutable();
            tiles_.addAll(other.tiles_);
          }
          onChanged();
        }
      } else {
        if (!other.tiles_.isEmpty()) {
          if (tilesBuilder_.isEmpty()) {
            tilesBuilder_.dispose();
            tilesBuilder_ = null;
            tiles_ = other.tiles_;
            bitField0_ = (bitField0_ & ~0x00000002);
            tilesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTilesFieldBuilder() : null;
          } else {
            tilesBuilder_.addAllMessages(other.tiles_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              layer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              io.ncraft.tilestream.Tile m =
                  input.readMessage(
                      io.ncraft.tilestream.Tile.parser(),
                      extensionRegistry);
              if (tilesBuilder_ == null) {
                ensureTilesIsMutable();
                tiles_.add(m);
              } else {
                tilesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object layer_ = "";
    /**
     * <code>string layer = 1;</code>
     * @return The layer.
     */
    public java.lang.String getLayer() {
      java.lang.Object ref = layer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        layer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @return The bytes for layer.
     */
    public com.google.protobuf.ByteString
        getLayerBytes() {
      java.lang.Object ref = layer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        layer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      layer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLayer() {
      layer_ = getDefaultInstance().getLayer();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The bytes for layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      layer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<io.ncraft.tilestream.Tile> tiles_ =
      java.util.Collections.emptyList();
    private void ensureTilesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        tiles_ = new java.util.ArrayList<io.ncraft.tilestream.Tile>(tiles_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Tile, io.ncraft.tilestream.Tile.Builder, io.ncraft.tilestream.TileOrBuilder> tilesBuilder_;

    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public java.util.List<io.ncraft.tilestream.Tile> getTilesList() {
      if (tilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tiles_);
      } else {
        return tilesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public int getTilesCount() {
      if (tilesBuilder_ == null) {
        return tiles_.size();
      } else {
        return tilesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public io.ncraft.tilestream.Tile getTiles(int index) {
      if (tilesBuilder_ == null) {
        return tiles_.get(index);
      } else {
        return tilesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder setTiles(
        int index, io.ncraft.tilestream.Tile value) {
      if (tilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTilesIsMutable();
        tiles_.set(index, value);
        onChanged();
      } else {
        tilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder setTiles(
        int index, io.ncraft.tilestream.Tile.Builder builderForValue) {
      if (tilesBuilder_ == null) {
        ensureTilesIsMutable();
        tiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        tilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder addTiles(io.ncraft.tilestream.Tile value) {
      if (tilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTilesIsMutable();
        tiles_.add(value);
        onChanged();
      } else {
        tilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder addTiles(
        int index, io.ncraft.tilestream.Tile value) {
      if (tilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTilesIsMutable();
        tiles_.add(index, value);
        onChanged();
      } else {
        tilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder addTiles(
        io.ncraft.tilestream.Tile.Builder builderForValue) {
      if (tilesBuilder_ == null) {
        ensureTilesIsMutable();
        tiles_.add(builderForValue.build());
        onChanged();
      } else {
        tilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder addTiles(
        int index, io.ncraft.tilestream.Tile.Builder builderForValue) {
      if (tilesBuilder_ == null) {
        ensureTilesIsMutable();
        tiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        tilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder addAllTiles(
        java.lang.Iterable<? extends io.ncraft.tilestream.Tile> values) {
      if (tilesBuilder_ == null) {
        ensureTilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tiles_);
        onChanged();
      } else {
        tilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder clearTiles() {
      if (tilesBuilder_ == null) {
        tiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        tilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public Builder removeTiles(int index) {
      if (tilesBuilder_ == null) {
        ensureTilesIsMutable();
        tiles_.remove(index);
        onChanged();
      } else {
        tilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public io.ncraft.tilestream.Tile.Builder getTilesBuilder(
        int index) {
      return getTilesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public io.ncraft.tilestream.TileOrBuilder getTilesOrBuilder(
        int index) {
      if (tilesBuilder_ == null) {
        return tiles_.get(index);  } else {
        return tilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public java.util.List<? extends io.ncraft.tilestream.TileOrBuilder> 
         getTilesOrBuilderList() {
      if (tilesBuilder_ != null) {
        return tilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tiles_);
      }
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public io.ncraft.tilestream.Tile.Builder addTilesBuilder() {
      return getTilesFieldBuilder().addBuilder(
          io.ncraft.tilestream.Tile.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public io.ncraft.tilestream.Tile.Builder addTilesBuilder(
        int index) {
      return getTilesFieldBuilder().addBuilder(
          index, io.ncraft.tilestream.Tile.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Tile tiles = 2;</code>
     */
    public java.util.List<io.ncraft.tilestream.Tile.Builder> 
         getTilesBuilderList() {
      return getTilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Tile, io.ncraft.tilestream.Tile.Builder, io.ncraft.tilestream.TileOrBuilder> 
        getTilesFieldBuilder() {
      if (tilesBuilder_ == null) {
        tilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.ncraft.tilestream.Tile, io.ncraft.tilestream.Tile.Builder, io.ncraft.tilestream.TileOrBuilder>(
                tiles_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        tiles_ = null;
      }
      return tilesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.v1.CreateTilesRequest)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.CreateTilesRequest)
  private static final io.ncraft.tilestream.v1.CreateTilesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.CreateTilesRequest();
  }

  public static io.ncraft.tilestream.v1.CreateTilesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTilesRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTilesRequest>() {
    @java.lang.Override
    public CreateTilesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTilesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTilesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.CreateTilesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

