// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/v1/tilestream.proto

package io.ncraft.tilestream.v1;

public interface ListLayersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.ListLayersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  java.util.List<io.ncraft.tilestream.Layer> 
      getLayersList();
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  io.ncraft.tilestream.Layer getLayers(int index);
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  int getLayersCount();
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  java.util.List<? extends io.ncraft.tilestream.LayerOrBuilder> 
      getLayersOrBuilderList();
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  io.ncraft.tilestream.LayerOrBuilder getLayersOrBuilder(
      int index);
}
