// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/v1/tilestream.proto

package io.ncraft.tilestream.v1;

public interface ListLayersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.ListLayersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prefix = 1;</code>
   * @return The prefix.
   */
  java.lang.String getPrefix();
  /**
   * <code>string prefix = 1;</code>
   * @return The bytes for prefix.
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>bool show_config = 2;</code>
   * @return The showConfig.
   */
  boolean getShowConfig();
}
