// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.ListLayersResponse}
 */
public final class ListLayersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.ListLayersResponse)
    ListLayersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      ListLayersResponse.class.getName());
  }
  // Use ListLayersResponse.newBuilder() to construct.
  private ListLayersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListLayersResponse() {
    layers_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_ListLayersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.ListLayersResponse.class, io.ncraft.tilestream.v1.ListLayersResponse.Builder.class);
  }

  public static final int LAYERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.ncraft.tilestream.Layer> layers_;
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.ncraft.tilestream.Layer> getLayersList() {
    return layers_;
  }
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.ncraft.tilestream.LayerOrBuilder> 
      getLayersOrBuilderList() {
    return layers_;
  }
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  @java.lang.Override
  public int getLayersCount() {
    return layers_.size();
  }
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.Layer getLayers(int index) {
    return layers_.get(index);
  }
  /**
   * <code>repeated .tilestream.Layer layers = 1;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.LayerOrBuilder getLayersOrBuilder(
      int index) {
    return layers_.get(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2000;
  private int totalCount_ = 0;
  /**
   * <code>int32 total_count = 2000;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2001;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextPageToken_ = "";
  /**
   * <code>string next_page_token = 2001;</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <code>string next_page_token = 2001;</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < layers_.size(); i++) {
      output.writeMessage(1, layers_.get(i));
    }
    if (totalCount_ != 0) {
      output.writeInt32(2000, totalCount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2001, nextPageToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < layers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, layers_.get(i));
    }
    if (totalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2000, totalCount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2001, nextPageToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.ListLayersResponse)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.ListLayersResponse other = (io.ncraft.tilestream.v1.ListLayersResponse) obj;

    if (!getLayersList()
        .equals(other.getLayersList())) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getNextPageToken()
        .equals(other.getNextPageToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLayersCount() > 0) {
      hash = (37 * hash) + LAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getLayersList().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCount();
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.v1.ListLayersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.v1.ListLayersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.ListLayersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.ListLayersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.ListLayersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.ListLayersResponse)
      io.ncraft.tilestream.v1.ListLayersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_ListLayersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.ListLayersResponse.class, io.ncraft.tilestream.v1.ListLayersResponse.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.ListLayersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (layersBuilder_ == null) {
        layers_ = java.util.Collections.emptyList();
      } else {
        layers_ = null;
        layersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalCount_ = 0;
      nextPageToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_ListLayersResponse_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.ListLayersResponse getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.ListLayersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.ListLayersResponse build() {
      io.ncraft.tilestream.v1.ListLayersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.ListLayersResponse buildPartial() {
      io.ncraft.tilestream.v1.ListLayersResponse result = new io.ncraft.tilestream.v1.ListLayersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.ncraft.tilestream.v1.ListLayersResponse result) {
      if (layersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          layers_ = java.util.Collections.unmodifiableList(layers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.layers_ = layers_;
      } else {
        result.layers_ = layersBuilder_.build();
      }
    }

    private void buildPartial0(io.ncraft.tilestream.v1.ListLayersResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalCount_ = totalCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nextPageToken_ = nextPageToken_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.ListLayersResponse) {
        return mergeFrom((io.ncraft.tilestream.v1.ListLayersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.ListLayersResponse other) {
      if (other == io.ncraft.tilestream.v1.ListLayersResponse.getDefaultInstance()) return this;
      if (layersBuilder_ == null) {
        if (!other.layers_.isEmpty()) {
          if (layers_.isEmpty()) {
            layers_ = other.layers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLayersIsMutable();
            layers_.addAll(other.layers_);
          }
          onChanged();
        }
      } else {
        if (!other.layers_.isEmpty()) {
          if (layersBuilder_.isEmpty()) {
            layersBuilder_.dispose();
            layersBuilder_ = null;
            layers_ = other.layers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            layersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLayersFieldBuilder() : null;
          } else {
            layersBuilder_.addAllMessages(other.layers_);
          }
        }
      }
      if (other.getTotalCount() != 0) {
        setTotalCount(other.getTotalCount());
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.ncraft.tilestream.Layer m =
                  input.readMessage(
                      io.ncraft.tilestream.Layer.parser(),
                      extensionRegistry);
              if (layersBuilder_ == null) {
                ensureLayersIsMutable();
                layers_.add(m);
              } else {
                layersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16000: {
              totalCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16000
            case 16010: {
              nextPageToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 16010
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.ncraft.tilestream.Layer> layers_ =
      java.util.Collections.emptyList();
    private void ensureLayersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        layers_ = new java.util.ArrayList<io.ncraft.tilestream.Layer>(layers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder> layersBuilder_;

    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public java.util.List<io.ncraft.tilestream.Layer> getLayersList() {
      if (layersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(layers_);
      } else {
        return layersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public int getLayersCount() {
      if (layersBuilder_ == null) {
        return layers_.size();
      } else {
        return layersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public io.ncraft.tilestream.Layer getLayers(int index) {
      if (layersBuilder_ == null) {
        return layers_.get(index);
      } else {
        return layersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder setLayers(
        int index, io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.set(index, value);
        onChanged();
      } else {
        layersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder setLayers(
        int index, io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.set(index, builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder addLayers(io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.add(value);
        onChanged();
      } else {
        layersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder addLayers(
        int index, io.ncraft.tilestream.Layer value) {
      if (layersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLayersIsMutable();
        layers_.add(index, value);
        onChanged();
      } else {
        layersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder addLayers(
        io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.add(builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder addLayers(
        int index, io.ncraft.tilestream.Layer.Builder builderForValue) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.add(index, builderForValue.build());
        onChanged();
      } else {
        layersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder addAllLayers(
        java.lang.Iterable<? extends io.ncraft.tilestream.Layer> values) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, layers_);
        onChanged();
      } else {
        layersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder clearLayers() {
      if (layersBuilder_ == null) {
        layers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        layersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public Builder removeLayers(int index) {
      if (layersBuilder_ == null) {
        ensureLayersIsMutable();
        layers_.remove(index);
        onChanged();
      } else {
        layersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public io.ncraft.tilestream.Layer.Builder getLayersBuilder(
        int index) {
      return getLayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public io.ncraft.tilestream.LayerOrBuilder getLayersOrBuilder(
        int index) {
      if (layersBuilder_ == null) {
        return layers_.get(index);  } else {
        return layersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public java.util.List<? extends io.ncraft.tilestream.LayerOrBuilder> 
         getLayersOrBuilderList() {
      if (layersBuilder_ != null) {
        return layersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(layers_);
      }
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public io.ncraft.tilestream.Layer.Builder addLayersBuilder() {
      return getLayersFieldBuilder().addBuilder(
          io.ncraft.tilestream.Layer.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public io.ncraft.tilestream.Layer.Builder addLayersBuilder(
        int index) {
      return getLayersFieldBuilder().addBuilder(
          index, io.ncraft.tilestream.Layer.getDefaultInstance());
    }
    /**
     * <code>repeated .tilestream.Layer layers = 1;</code>
     */
    public java.util.List<io.ncraft.tilestream.Layer.Builder> 
         getLayersBuilderList() {
      return getLayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder> 
        getLayersFieldBuilder() {
      if (layersBuilder_ == null) {
        layersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.ncraft.tilestream.Layer, io.ncraft.tilestream.Layer.Builder, io.ncraft.tilestream.LayerOrBuilder>(
                layers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        layers_ = null;
      }
      return layersBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>int32 total_count = 2000;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int32 total_count = 2000;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {

      totalCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_count = 2000;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <code>string next_page_token = 2001;</code>
     * @return The nextPageToken.
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string next_page_token = 2001;</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string next_page_token = 2001;</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string next_page_token = 2001;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string next_page_token = 2001;</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nextPageToken_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.v1.ListLayersResponse)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.ListLayersResponse)
  private static final io.ncraft.tilestream.v1.ListLayersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.ListLayersResponse();
  }

  public static io.ncraft.tilestream.v1.ListLayersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListLayersResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListLayersResponse>() {
    @java.lang.Override
    public ListLayersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListLayersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListLayersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.ListLayersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

