// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

public final class TilestreamProto {
  private TilestreamProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TilestreamProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_CreateTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchCreateTilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateTilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_GetTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetTileInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_GetTileInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_UpdateTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_CreateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchCreateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchCreateLayerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchCreateLayerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_UpdateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchUpdateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchUpdateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_DeleteLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_DeleteLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_GetLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchGetLayersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchGetLayersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchGetLayersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_BatchGetLayersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_ListLayersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_ListLayersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_ListLayersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036tilestream/v1/tilestream.proto\022\rtilest" +
      "ream.v1\032\032mojo/core/field_mask.proto\032\024moj" +
      "o/core/null.proto\032\030mojo/core/ordering.pr" +
      "oto\032\017mojo/mojo.proto\032\026tilestream/layer.p" +
      "roto\032\025tilestream/tile.proto\032\032tilestream/" +
      "tile_info.proto\"W\n\021CreateTileRequest\022\r\n\005" +
      "layer\030\001 \001(\t\022\r\n\005level\030\002 \001(\005\022\t\n\001x\030\003 \001(\005\022\t\n" +
      "\001y\030\004 \001(\005\022\016\n\006format\030\005 \001(\t\"\031\n\027BatchCreateT" +
      "ilesRequest\"D\n\022CreateTilesRequest\022\r\n\005lay" +
      "er\030\001 \001(\t\022\037\n\005tiles\030\002 \003(\0132\020.tilestream.Til" +
      "e\"T\n\016GetTileRequest\022\r\n\005layer\030\001 \001(\t\022\r\n\005le" +
      "vel\030\002 \001(\005\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\016\n\006forma" +
      "t\030\005 \001(\t\"#\n\022GetTileInfoRequest\022\r\n\005layer\030\001" +
      " \001(\t\"w\n\021UpdateTileRequest\022\r\n\005layer\030\001 \001(\t" +
      "\022\r\n\005level\030\002 \001(\005\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\016\n" +
      "\006format\030\005 \001(\t\022\036\n\004tile\030\006 \001(\0132\020.tilestream" +
      ".Tile\"J\n\025UpdateTileInfoRequest\022\r\n\005layer\030" +
      "\001 \001(\t\022\"\n\004info\030\002 \001(\0132\024.tilestream.TileInf" +
      "o\"6\n\022CreateLayerRequest\022 \n\005layer\030\001 \001(\0132\021" +
      ".tilestream.Layer\"<\n\027BatchCreateLayerReq" +
      "uest\022!\n\006layers\030\002 \003(\0132\021.tilestream.Layer\"" +
      "=\n\030BatchCreateLayerResponse\022!\n\006layers\030\001 " +
      "\003(\0132\021.tilestream.Layer\"B\n\022UpdateLayerReq" +
      "uest\022\n\n\002id\030\001 \001(\t\022 \n\005layer\030\002 \001(\0132\021.tilest" +
      "ream.Layer\"<\n\027BatchUpdateLayerRequest\022!\n" +
      "\006layers\030\002 \003(\0132\021.tilestream.Layer\"#\n\022Dele" +
      "teLayerRequest\022\r\n\005layer\030\001 \001(\t\" \n\017GetLaye" +
      "rRequest\022\r\n\005layer\030\001 \001(\t\"\'\n\025BatchGetLayer" +
      "sRequest\022\016\n\006layers\030\001 \003(\t\";\n\026BatchGetLaye" +
      "rsResponse\022!\n\006layers\030\001 \003(\0132\021.tilestream." +
      "Layer\"\315\001\n\021ListLayersRequest\022\016\n\006prefix\030\001 " +
      "\001(\t\022\022\n\tpage_size\030\320\017 \001(\005\022\023\n\npage_token\030\321\017" +
      " \001(\t\022\r\n\004skip\030\322\017 \001(\005\022\017\n\006filter\030\333\017 \001(\t\022#\n\005" +
      "order\030\334\017 \001(\0132\023.mojo.core.Ordering\022)\n\nfie" +
      "ld_mask\030\335\017 \001(\0132\024.mojo.core.FieldMask\022\017\n\006" +
      "unique\030\336\017 \001(\010\"g\n\022ListLayersResponse\022!\n\006l" +
      "ayers\030\001 \003(\0132\021.tilestream.Layer\022\024\n\013total_" +
      "count\030\320\017 \001(\005\022\030\n\017next_page_token\030\321\017 \001(\t2\357" +
      "\010\n\nTilestream\022A\n\013create_tile\022 .tilestrea" +
      "m.v1.CreateTileRequest\032\020.tilestream.Tile" +
      "\022M\n\022batch_create_tiles\022&.tilestream.v1.B" +
      "atchCreateTilesRequest\032\017.mojo.core.Null\022" +
      "B\n\014create_tiles\022!.tilestream.v1.CreateTi" +
      "lesRequest\032\017.mojo.core.Null\022;\n\010get_tile\022" +
      "\035.tilestream.v1.GetTileRequest\032\020.tilestr" +
      "eam.Tile\022H\n\rget_tile_info\022!.tilestream.v" +
      "1.GetTileInfoRequest\032\024.tilestream.TileIn" +
      "fo\022@\n\013update_tile\022 .tilestream.v1.Update" +
      "TileRequest\032\017.mojo.core.Null\022I\n\020update_t" +
      "ile_info\022$.tilestream.v1.UpdateTileInfoR" +
      "equest\032\017.mojo.core.Null\022D\n\014create_layer\022" +
      "!.tilestream.v1.CreateLayerRequest\032\021.til" +
      "estream.Layer\022e\n\022batch_create_layer\022&.ti" +
      "lestream.v1.BatchCreateLayerRequest\032\'.ti" +
      "lestream.v1.BatchCreateLayerResponse\022B\n\014" +
      "update_layer\022!.tilestream.v1.UpdateLayer" +
      "Request\032\017.mojo.core.Null\022M\n\022batch_update" +
      "_layer\022&.tilestream.v1.BatchUpdateLayerR" +
      "equest\032\017.mojo.core.Null\022B\n\014delete_layer\022" +
      "!.tilestream.v1.DeleteLayerRequest\032\017.moj" +
      "o.core.Null\022>\n\tget_layer\022\036.tilestream.v1" +
      ".GetLayerRequest\032\021.tilestream.Layer\022_\n\020b" +
      "atch_get_layers\022$.tilestream.v1.BatchGet" +
      "LayersRequest\032%.tilestream.v1.BatchGetLa" +
      "yersResponse\022R\n\013list_layers\022 .tilestream" +
      ".v1.ListLayersRequest\032!.tilestream.v1.Li" +
      "stLayersResponseBm\n\027io.ncraft.tilestream" +
      ".v1B\017TilestreamProtoP\001Z?github.com/ncraf" +
      "t-io/tilestream/go/pkg/tilestream/v1;til" +
      "estreamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.FieldMaskProto.getDescriptor(),
          org.mojolang.mojo.core.NullProto.getDescriptor(),
          org.mojolang.mojo.core.OrderingProto.getDescriptor(),
          org.mojolang.mojo.MojoProtos.getDescriptor(),
          io.ncraft.tilestream.LayerProto.getDescriptor(),
          io.ncraft.tilestream.TileProto.getDescriptor(),
          io.ncraft.tilestream.TileInfoProto.getDescriptor(),
        });
    internal_static_tilestream_v1_CreateTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_v1_CreateTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_CreateTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", });
    internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tilestream_v1_BatchCreateTilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tilestream_v1_CreateTilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_CreateTilesRequest_descriptor,
        new java.lang.String[] { "Layer", "Tiles", });
    internal_static_tilestream_v1_GetTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tilestream_v1_GetTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_GetTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", });
    internal_static_tilestream_v1_GetTileInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tilestream_v1_GetTileInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_GetTileInfoRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_UpdateTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tilestream_v1_UpdateTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", "Tile", });
    internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor,
        new java.lang.String[] { "Layer", "Info", });
    internal_static_tilestream_v1_CreateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tilestream_v1_CreateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_CreateLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tilestream_v1_BatchCreateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchCreateLayerRequest_descriptor,
        new java.lang.String[] { "Layers", });
    internal_static_tilestream_v1_BatchCreateLayerResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tilestream_v1_BatchCreateLayerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchCreateLayerResponse_descriptor,
        new java.lang.String[] { "Layers", });
    internal_static_tilestream_v1_UpdateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tilestream_v1_UpdateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateLayerRequest_descriptor,
        new java.lang.String[] { "Id", "Layer", });
    internal_static_tilestream_v1_BatchUpdateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tilestream_v1_BatchUpdateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchUpdateLayerRequest_descriptor,
        new java.lang.String[] { "Layers", });
    internal_static_tilestream_v1_DeleteLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tilestream_v1_DeleteLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_DeleteLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_GetLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tilestream_v1_GetLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_GetLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_BatchGetLayersRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tilestream_v1_BatchGetLayersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchGetLayersRequest_descriptor,
        new java.lang.String[] { "Layers", });
    internal_static_tilestream_v1_BatchGetLayersResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tilestream_v1_BatchGetLayersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_BatchGetLayersResponse_descriptor,
        new java.lang.String[] { "Layers", });
    internal_static_tilestream_v1_ListLayersRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tilestream_v1_ListLayersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_ListLayersRequest_descriptor,
        new java.lang.String[] { "Prefix", "PageSize", "PageToken", "Skip", "Filter", "Order", "FieldMask", "Unique", });
    internal_static_tilestream_v1_ListLayersResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_v1_ListLayersResponse_descriptor,
        new java.lang.String[] { "Layers", "TotalCount", "NextPageToken", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.core.FieldMaskProto.getDescriptor();
    org.mojolang.mojo.core.NullProto.getDescriptor();
    org.mojolang.mojo.core.OrderingProto.getDescriptor();
    org.mojolang.mojo.MojoProtos.getDescriptor();
    io.ncraft.tilestream.LayerProto.getDescriptor();
    io.ncraft.tilestream.TileProto.getDescriptor();
    io.ncraft.tilestream.TileInfoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
