// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/v1/tilestream.proto

package io.ncraft.tilestream.v1;

public final class TilestreamProto {
  private TilestreamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_CreateTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_BatchCreateTilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateTilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_GetTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetTileInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_GetTileInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateTileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_UpdateTileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_CreateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_CreateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_UpdateLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_UpdateLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_DeleteLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_DeleteLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_GetLayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_GetLayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_ListLayersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_ListLayersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_v1_ListLayersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036tilestream/v1/tilestream.proto\022\rtilest" +
      "ream.v1\032\024mojo/core/null.proto\032\017mojo/mojo" +
      ".proto\032\026tilestream/layer.proto\032\025tilestre" +
      "am/tile.proto\032\032tilestream/tile_info.prot" +
      "o\"W\n\021CreateTileRequest\022\r\n\005layer\030\001 \001(\t\022\r\n" +
      "\005level\030\002 \001(\005\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\016\n\006fo" +
      "rmat\030\005 \001(\t\"\031\n\027BatchCreateTilesRequest\"D\n" +
      "\022CreateTilesRequest\022\r\n\005layer\030\001 \001(\t\022\037\n\005ti" +
      "les\030\002 \003(\0132\020.tilestream.Tile\"T\n\016GetTileRe" +
      "quest\022\r\n\005layer\030\001 \001(\t\022\r\n\005level\030\002 \001(\005\022\t\n\001x" +
      "\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\016\n\006format\030\005 \001(\t\"#\n\022Get" +
      "TileInfoRequest\022\r\n\005layer\030\001 \001(\t\"w\n\021Update" +
      "TileRequest\022\r\n\005layer\030\001 \001(\t\022\r\n\005level\030\002 \001(" +
      "\005\022\t\n\001x\030\003 \001(\005\022\t\n\001y\030\004 \001(\005\022\016\n\006format\030\005 \001(\t\022" +
      "\036\n\004tile\030\006 \001(\0132\020.tilestream.Tile\"J\n\025Updat" +
      "eTileInfoRequest\022\r\n\005layer\030\001 \001(\t\022\"\n\004info\030" +
      "\002 \001(\0132\024.tilestream.TileInfo\"6\n\022CreateLay" +
      "erRequest\022 \n\005layer\030\001 \001(\0132\021.tilestream.La" +
      "yer\"B\n\022UpdateLayerRequest\022\n\n\002id\030\001 \001(\t\022 \n" +
      "\005layer\030\002 \001(\0132\021.tilestream.Layer\"#\n\022Delet" +
      "eLayerRequest\022\r\n\005layer\030\001 \001(\t\" \n\017GetLayer" +
      "Request\022\r\n\005layer\030\001 \001(\t\"8\n\021ListLayersRequ" +
      "est\022\016\n\006prefix\030\001 \001(\t\022\023\n\013show_config\030\002 \001(\010" +
      "\"7\n\022ListLayersResponse\022!\n\006layers\030\001 \003(\0132\021" +
      ".tilestream.Layer2\330\006\n\nTilestream\022A\n\013crea" +
      "te_tile\022 .tilestream.v1.CreateTileReques" +
      "t\032\020.tilestream.Tile\022M\n\022batch_create_tile" +
      "s\022&.tilestream.v1.BatchCreateTilesReques" +
      "t\032\017.mojo.core.Null\022B\n\014create_tiles\022!.til" +
      "estream.v1.CreateTilesRequest\032\017.mojo.cor" +
      "e.Null\022;\n\010get_tile\022\035.tilestream.v1.GetTi" +
      "leRequest\032\020.tilestream.Tile\022H\n\rget_tile_" +
      "info\022!.tilestream.v1.GetTileInfoRequest\032" +
      "\024.tilestream.TileInfo\022@\n\013update_tile\022 .t" +
      "ilestream.v1.UpdateTileRequest\032\017.mojo.co" +
      "re.Null\022I\n\020update_tile_info\022$.tilestream" +
      ".v1.UpdateTileInfoRequest\032\017.mojo.core.Nu" +
      "ll\022D\n\014create_layer\022!.tilestream.v1.Creat" +
      "eLayerRequest\032\021.tilestream.Layer\022B\n\014upda" +
      "te_layer\022!.tilestream.v1.UpdateLayerRequ" +
      "est\032\017.mojo.core.Null\022B\n\014delete_layer\022!.t" +
      "ilestream.v1.DeleteLayerRequest\032\017.mojo.c" +
      "ore.Null\022>\n\tget_layer\022\036.tilestream.v1.Ge" +
      "tLayerRequest\032\021.tilestream.Layer\022R\n\013list" +
      "_layers\022 .tilestream.v1.ListLayersReques" +
      "t\032!.tilestream.v1.ListLayersResponseBm\n\027" +
      "io.ncraft.tilestream.v1B\017TilestreamProto" +
      "P\001Z?github.com/ncraft-io/tilestream/go/p" +
      "kg/tilestream/v1;tilestreamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.NullProto.getDescriptor(),
          com.google.protobuf.MojoProtos.getDescriptor(),
          io.ncraft.tilestream.LayerProto.getDescriptor(),
          io.ncraft.tilestream.TileProto.getDescriptor(),
          io.ncraft.tilestream.TileInfoProto.getDescriptor(),
        });
    internal_static_tilestream_v1_CreateTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_v1_CreateTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_CreateTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", });
    internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tilestream_v1_BatchCreateTilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_BatchCreateTilesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tilestream_v1_CreateTilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tilestream_v1_CreateTilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_CreateTilesRequest_descriptor,
        new java.lang.String[] { "Layer", "Tiles", });
    internal_static_tilestream_v1_GetTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tilestream_v1_GetTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_GetTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", });
    internal_static_tilestream_v1_GetTileInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tilestream_v1_GetTileInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_GetTileInfoRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_UpdateTileRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tilestream_v1_UpdateTileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateTileRequest_descriptor,
        new java.lang.String[] { "Layer", "Level", "X", "Y", "Format", "Tile", });
    internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor,
        new java.lang.String[] { "Layer", "Info", });
    internal_static_tilestream_v1_CreateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tilestream_v1_CreateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_CreateLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_UpdateLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tilestream_v1_UpdateLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_UpdateLayerRequest_descriptor,
        new java.lang.String[] { "Id", "Layer", });
    internal_static_tilestream_v1_DeleteLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tilestream_v1_DeleteLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_DeleteLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_GetLayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tilestream_v1_GetLayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_GetLayerRequest_descriptor,
        new java.lang.String[] { "Layer", });
    internal_static_tilestream_v1_ListLayersRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tilestream_v1_ListLayersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_ListLayersRequest_descriptor,
        new java.lang.String[] { "Prefix", "ShowConfig", });
    internal_static_tilestream_v1_ListLayersResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tilestream_v1_ListLayersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_v1_ListLayersResponse_descriptor,
        new java.lang.String[] { "Layers", });
    org.mojolang.mojo.core.NullProto.getDescriptor();
    com.google.protobuf.MojoProtos.getDescriptor();
    io.ncraft.tilestream.LayerProto.getDescriptor();
    io.ncraft.tilestream.TileProto.getDescriptor();
    io.ncraft.tilestream.TileInfoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
