// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

public interface UpdateTileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.UpdateTileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string layer = 1;</code>
   * @return The layer.
   */
  java.lang.String getLayer();
  /**
   * <code>string layer = 1;</code>
   * @return The bytes for layer.
   */
  com.google.protobuf.ByteString
      getLayerBytes();

  /**
   * <code>int32 level = 2;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>string format = 5;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 5;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>.tilestream.Tile tile = 6;</code>
   * @return Whether the tile field is set.
   */
  boolean hasTile();
  /**
   * <code>.tilestream.Tile tile = 6;</code>
   * @return The tile.
   */
  io.ncraft.tilestream.Tile getTile();
  /**
   * <code>.tilestream.Tile tile = 6;</code>
   */
  io.ncraft.tilestream.TileOrBuilder getTileOrBuilder();
}
