// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

public interface UpdateTileInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.UpdateTileInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string layer = 1;</code>
   * @return The layer.
   */
  java.lang.String getLayer();
  /**
   * <code>string layer = 1;</code>
   * @return The bytes for layer.
   */
  com.google.protobuf.ByteString
      getLayerBytes();

  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return The info.
   */
  io.ncraft.tilestream.TileInfo getInfo();
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   */
  io.ncraft.tilestream.TileInfoOrBuilder getInfoOrBuilder();
}
