// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/v1/tilestream.proto

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.UpdateTileInfoRequest}
 */
public final class UpdateTileInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.UpdateTileInfoRequest)
    UpdateTileInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateTileInfoRequest.newBuilder() to construct.
  private UpdateTileInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateTileInfoRequest() {
    layer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateTileInfoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.UpdateTileInfoRequest.class, io.ncraft.tilestream.v1.UpdateTileInfoRequest.Builder.class);
  }

  public static final int LAYER_FIELD_NUMBER = 1;
  private volatile java.lang.Object layer_;
  /**
   * <code>string layer = 1;</code>
   * @return The layer.
   */
  @java.lang.Override
  public java.lang.String getLayer() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      layer_ = s;
      return s;
    }
  }
  /**
   * <code>string layer = 1;</code>
   * @return The bytes for layer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLayerBytes() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      layer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFO_FIELD_NUMBER = 2;
  private io.ncraft.tilestream.TileInfo info_;
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  @java.lang.Override
  public boolean hasInfo() {
    return info_ != null;
  }
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return The info.
   */
  @java.lang.Override
  public io.ncraft.tilestream.TileInfo getInfo() {
    return info_ == null ? io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
  }
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.TileInfoOrBuilder getInfoOrBuilder() {
    return getInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(layer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, layer_);
    }
    if (info_ != null) {
      output.writeMessage(2, getInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(layer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, layer_);
    }
    if (info_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.UpdateTileInfoRequest)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.UpdateTileInfoRequest other = (io.ncraft.tilestream.v1.UpdateTileInfoRequest) obj;

    if (!getLayer()
        .equals(other.getLayer())) return false;
    if (hasInfo() != other.hasInfo()) return false;
    if (hasInfo()) {
      if (!getInfo()
          .equals(other.getInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAYER_FIELD_NUMBER;
    hash = (53 * hash) + getLayer().hashCode();
    if (hasInfo()) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.UpdateTileInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.UpdateTileInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.UpdateTileInfoRequest)
      io.ncraft.tilestream.v1.UpdateTileInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.UpdateTileInfoRequest.class, io.ncraft.tilestream.v1.UpdateTileInfoRequest.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.UpdateTileInfoRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      layer_ = "";

      if (infoBuilder_ == null) {
        info_ = null;
      } else {
        info_ = null;
        infoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.UpdateTileInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest build() {
      io.ncraft.tilestream.v1.UpdateTileInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest buildPartial() {
      io.ncraft.tilestream.v1.UpdateTileInfoRequest result = new io.ncraft.tilestream.v1.UpdateTileInfoRequest(this);
      result.layer_ = layer_;
      if (infoBuilder_ == null) {
        result.info_ = info_;
      } else {
        result.info_ = infoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.UpdateTileInfoRequest) {
        return mergeFrom((io.ncraft.tilestream.v1.UpdateTileInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.UpdateTileInfoRequest other) {
      if (other == io.ncraft.tilestream.v1.UpdateTileInfoRequest.getDefaultInstance()) return this;
      if (!other.getLayer().isEmpty()) {
        layer_ = other.layer_;
        onChanged();
      }
      if (other.hasInfo()) {
        mergeInfo(other.getInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              layer_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInfoFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object layer_ = "";
    /**
     * <code>string layer = 1;</code>
     * @return The layer.
     */
    public java.lang.String getLayer() {
      java.lang.Object ref = layer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        layer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @return The bytes for layer.
     */
    public com.google.protobuf.ByteString
        getLayerBytes() {
      java.lang.Object ref = layer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        layer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      layer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLayer() {
      
      layer_ = getDefaultInstance().getLayer();
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The bytes for layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      layer_ = value;
      onChanged();
      return this;
    }

    private io.ncraft.tilestream.TileInfo info_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder> infoBuilder_;
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return infoBuilder_ != null || info_ != null;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     * @return The info.
     */
    public io.ncraft.tilestream.TileInfo getInfo() {
      if (infoBuilder_ == null) {
        return info_ == null ? io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
      } else {
        return infoBuilder_.getMessage();
      }
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder setInfo(io.ncraft.tilestream.TileInfo value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
        onChanged();
      } else {
        infoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder setInfo(
        io.ncraft.tilestream.TileInfo.Builder builderForValue) {
      if (infoBuilder_ == null) {
        info_ = builderForValue.build();
        onChanged();
      } else {
        infoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder mergeInfo(io.ncraft.tilestream.TileInfo value) {
      if (infoBuilder_ == null) {
        if (info_ != null) {
          info_ =
            io.ncraft.tilestream.TileInfo.newBuilder(info_).mergeFrom(value).buildPartial();
        } else {
          info_ = value;
        }
        onChanged();
      } else {
        infoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder clearInfo() {
      if (infoBuilder_ == null) {
        info_ = null;
        onChanged();
      } else {
        info_ = null;
        infoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public io.ncraft.tilestream.TileInfo.Builder getInfoBuilder() {
      
      onChanged();
      return getInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public io.ncraft.tilestream.TileInfoOrBuilder getInfoOrBuilder() {
      if (infoBuilder_ != null) {
        return infoBuilder_.getMessageOrBuilder();
      } else {
        return info_ == null ?
            io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
      }
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder> 
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder>(
                getInfo(),
                getParentForChildren(),
                isClean());
        info_ = null;
      }
      return infoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tilestream.v1.UpdateTileInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.UpdateTileInfoRequest)
  private static final io.ncraft.tilestream.v1.UpdateTileInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.UpdateTileInfoRequest();
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateTileInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateTileInfoRequest>() {
    @java.lang.Override
    public UpdateTileInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateTileInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateTileInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

