// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

/**
 * Protobuf type {@code tilestream.v1.UpdateTileInfoRequest}
 */
public final class UpdateTileInfoRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.v1.UpdateTileInfoRequest)
    UpdateTileInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      UpdateTileInfoRequest.class.getName());
  }
  // Use UpdateTileInfoRequest.newBuilder() to construct.
  private UpdateTileInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateTileInfoRequest() {
    layer_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.v1.UpdateTileInfoRequest.class, io.ncraft.tilestream.v1.UpdateTileInfoRequest.Builder.class);
  }

  private int bitField0_;
  public static final int LAYER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object layer_ = "";
  /**
   * <code>string layer = 1;</code>
   * @return The layer.
   */
  @java.lang.Override
  public java.lang.String getLayer() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      layer_ = s;
      return s;
    }
  }
  /**
   * <code>string layer = 1;</code>
   * @return The bytes for layer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLayerBytes() {
    java.lang.Object ref = layer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      layer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFO_FIELD_NUMBER = 2;
  private io.ncraft.tilestream.TileInfo info_;
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  @java.lang.Override
  public boolean hasInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   * @return The info.
   */
  @java.lang.Override
  public io.ncraft.tilestream.TileInfo getInfo() {
    return info_ == null ? io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
  }
  /**
   * <code>.tilestream.TileInfo info = 2;</code>
   */
  @java.lang.Override
  public io.ncraft.tilestream.TileInfoOrBuilder getInfoOrBuilder() {
    return info_ == null ? io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layer_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, layer_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(layer_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, layer_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.v1.UpdateTileInfoRequest)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.v1.UpdateTileInfoRequest other = (io.ncraft.tilestream.v1.UpdateTileInfoRequest) obj;

    if (!getLayer()
        .equals(other.getLayer())) return false;
    if (hasInfo() != other.hasInfo()) return false;
    if (hasInfo()) {
      if (!getInfo()
          .equals(other.getInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAYER_FIELD_NUMBER;
    hash = (53 * hash) + getLayer().hashCode();
    if (hasInfo()) {
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.v1.UpdateTileInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.v1.UpdateTileInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.v1.UpdateTileInfoRequest)
      io.ncraft.tilestream.v1.UpdateTileInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.v1.UpdateTileInfoRequest.class, io.ncraft.tilestream.v1.UpdateTileInfoRequest.Builder.class);
    }

    // Construct using io.ncraft.tilestream.v1.UpdateTileInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      layer_ = "";
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.v1.TilestreamProto.internal_static_tilestream_v1_UpdateTileInfoRequest_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstanceForType() {
      return io.ncraft.tilestream.v1.UpdateTileInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest build() {
      io.ncraft.tilestream.v1.UpdateTileInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.v1.UpdateTileInfoRequest buildPartial() {
      io.ncraft.tilestream.v1.UpdateTileInfoRequest result = new io.ncraft.tilestream.v1.UpdateTileInfoRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.ncraft.tilestream.v1.UpdateTileInfoRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.layer_ = layer_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.info_ = infoBuilder_ == null
            ? info_
            : infoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.v1.UpdateTileInfoRequest) {
        return mergeFrom((io.ncraft.tilestream.v1.UpdateTileInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.v1.UpdateTileInfoRequest other) {
      if (other == io.ncraft.tilestream.v1.UpdateTileInfoRequest.getDefaultInstance()) return this;
      if (!other.getLayer().isEmpty()) {
        layer_ = other.layer_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasInfo()) {
        mergeInfo(other.getInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              layer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object layer_ = "";
    /**
     * <code>string layer = 1;</code>
     * @return The layer.
     */
    public java.lang.String getLayer() {
      java.lang.Object ref = layer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        layer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @return The bytes for layer.
     */
    public com.google.protobuf.ByteString
        getLayerBytes() {
      java.lang.Object ref = layer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        layer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      layer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLayer() {
      layer_ = getDefaultInstance().getLayer();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string layer = 1;</code>
     * @param value The bytes for layer to set.
     * @return This builder for chaining.
     */
    public Builder setLayerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      layer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private io.ncraft.tilestream.TileInfo info_;
    private com.google.protobuf.SingleFieldBuilder<
        io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder> infoBuilder_;
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     * @return Whether the info field is set.
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     * @return The info.
     */
    public io.ncraft.tilestream.TileInfo getInfo() {
      if (infoBuilder_ == null) {
        return info_ == null ? io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
      } else {
        return infoBuilder_.getMessage();
      }
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder setInfo(io.ncraft.tilestream.TileInfo value) {
      if (infoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        info_ = value;
      } else {
        infoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder setInfo(
        io.ncraft.tilestream.TileInfo.Builder builderForValue) {
      if (infoBuilder_ == null) {
        info_ = builderForValue.build();
      } else {
        infoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder mergeInfo(io.ncraft.tilestream.TileInfo value) {
      if (infoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          info_ != null &&
          info_ != io.ncraft.tilestream.TileInfo.getDefaultInstance()) {
          getInfoBuilder().mergeFrom(value);
        } else {
          info_ = value;
        }
      } else {
        infoBuilder_.mergeFrom(value);
      }
      if (info_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public Builder clearInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      info_ = null;
      if (infoBuilder_ != null) {
        infoBuilder_.dispose();
        infoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public io.ncraft.tilestream.TileInfo.Builder getInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    public io.ncraft.tilestream.TileInfoOrBuilder getInfoOrBuilder() {
      if (infoBuilder_ != null) {
        return infoBuilder_.getMessageOrBuilder();
      } else {
        return info_ == null ?
            io.ncraft.tilestream.TileInfo.getDefaultInstance() : info_;
      }
    }
    /**
     * <code>.tilestream.TileInfo info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder> 
        getInfoFieldBuilder() {
      if (infoBuilder_ == null) {
        infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.ncraft.tilestream.TileInfo, io.ncraft.tilestream.TileInfo.Builder, io.ncraft.tilestream.TileInfoOrBuilder>(
                getInfo(),
                getParentForChildren(),
                isClean());
        info_ = null;
      }
      return infoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.v1.UpdateTileInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:tilestream.v1.UpdateTileInfoRequest)
  private static final io.ncraft.tilestream.v1.UpdateTileInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.v1.UpdateTileInfoRequest();
  }

  public static io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateTileInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateTileInfoRequest>() {
    @java.lang.Override
    public UpdateTileInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateTileInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateTileInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.v1.UpdateTileInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

