// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/v1/tilestream.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.v1;

public interface UpdateLayerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.v1.UpdateLayerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.tilestream.Layer layer = 2;</code>
   * @return Whether the layer field is set.
   */
  boolean hasLayer();
  /**
   * <code>.tilestream.Layer layer = 2;</code>
   * @return The layer.
   */
  io.ncraft.tilestream.Layer getLayer();
  /**
   * <code>.tilestream.Layer layer = 2;</code>
   */
  io.ncraft.tilestream.LayerOrBuilder getLayerOrBuilder();
}
