// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package tilestream

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/mojo/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("tilestream.BatchGetLayersResponse", &BatchGetLayersResponseCodec{})
	core.RegisterJSONTypeEncoder("tilestream.BatchGetLayersResponse", &BatchGetLayersResponseCodec{})
}

type BatchGetLayersResponseCodec struct {
}

func (codec *BatchGetLayersResponseCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	batchGetLayersResponse := (*BatchGetLayersResponse)(ptr)
	if any.ValueType() == jsoniter.ArrayValue {
		any.ToVal(&batchGetLayersResponse.Layers)
	}
}

func (codec *BatchGetLayersResponseCodec) IsEmpty(ptr unsafe.Pointer) bool {
	batchGetLayersResponse := (*BatchGetLayersResponse)(ptr)
	return batchGetLayersResponse == nil || len(batchGetLayersResponse.Layers) == 0
}

func (codec *BatchGetLayersResponseCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	batchGetLayersResponse := (*BatchGetLayersResponse)(ptr)
	if len(batchGetLayersResponse.Layers) > 0 {
		stream.WriteVal(batchGetLayersResponse.Layers)
	} else {
		stream.WriteRaw("[]")
	}
}
