// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package tilestream

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/mojo/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("tilestream.BatchCreateLayerResponse", &BatchCreateLayerResponseCodec{})
	core.RegisterJSONTypeEncoder("tilestream.BatchCreateLayerResponse", &BatchCreateLayerResponseCodec{})
}

type BatchCreateLayerResponseCodec struct {
}

func (codec *BatchCreateLayerResponseCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	batchCreateLayerResponse := (*BatchCreateLayerResponse)(ptr)
	if any.ValueType() == jsoniter.ArrayValue {
		any.ToVal(&batchCreateLayerResponse.Layers)
	}
}

func (codec *BatchCreateLayerResponseCodec) IsEmpty(ptr unsafe.Pointer) bool {
	batchCreateLayerResponse := (*BatchCreateLayerResponse)(ptr)
	return batchCreateLayerResponse == nil || len(batchCreateLayerResponse.Layers) == 0
}

func (codec *BatchCreateLayerResponseCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	batchCreateLayerResponse := (*BatchCreateLayerResponse)(ptr)
	if len(batchCreateLayerResponse.Layers) > 0 {
		stream.WriteVal(batchCreateLayerResponse.Layers)
	} else {
		stream.WriteRaw("[]")
	}
}
