// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package tilestream

import (
	"unsafe"

	jsoniter "github.com/json-iterator/go"
	"github.com/mojo-lang/mojo/go/pkg/mojo/core"
)

func init() {
	core.RegisterJSONTypeDecoder("tilestream.LayerConfig", &LayerConfigCodec{})
	core.RegisterJSONTypeEncoder("tilestream.LayerConfig", &LayerConfigCodec{})
}

type LayerConfigCodec struct {
}

func (codec *LayerConfigCodec) Decode(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	any := iter.ReadAny()
	layerConfig := (*LayerConfig)(ptr)
	layerConfig.Init()

	any.ToVal(layerConfig.Object)
}

func (codec *LayerConfigCodec) IsEmpty(ptr unsafe.Pointer) bool {
	layerConfig := (*LayerConfig)(ptr)
	return layerConfig == nil || layerConfig.Object == nil
}

func (codec *LayerConfigCodec) Encode(ptr unsafe.Pointer, stream *jsoniter.Stream) {
	layerConfig := (*LayerConfig)(ptr)
	stream.WriteVal(layerConfig.Object)
}
