// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.

package tilestream

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/mojo-lang/core/go/pkg/mojo/core"
)

var VectorTileGeomTypeNames = map[int32]string{
	0: "UNKNOWN",
	1: "POINT",
	2: "LINESTRING",
	3: "POLYGON",
}

var VectorTileGeomTypeValues = map[string]VectorTile_GeomType{
	"UNKNOWN":    VectorTile_GEOM_TYPE_UNKNOWN,
	"POINT":      VectorTile_GEOM_TYPE_POINT,
	"LINESTRING": VectorTile_GEOM_TYPE_LINESTRING,
	"POLYGON":    VectorTile_GEOM_TYPE_POLYGON,
}

func (x VectorTile_GeomType) Format() string {
	v := int32(x)
	if s, ok := VectorTileGeomTypeNames[v]; ok {
		if v == 0 && "unspecified" == strings.ToLower(s) {
			return ""
		}
		return s
	}
	if v == 0 {
		return ""
	}
	return strconv.Itoa(int(v))
}

func (x VectorTile_GeomType) ToString() string {
	return x.Format()
}

func (x *VectorTile_GeomType) Parse(value string) error {
	if x != nil && len(value) > 0 {
		if s, ok := VectorTileGeomTypeValues[value]; ok {
			*x = s
		} else {
			v := core.CaseStyler("snake")(value)
			if s, ok = VectorTileGeomTypeValues[v]; ok {
				*x = s
			} else {
				return fmt.Errorf("invalid VectorTile_GeomType: %s", value)
			}
		}
	}
	return nil
}

func ParseVectorTile_GeomType(value string) (VectorTile_GeomType, error) {
	var v VectorTile_GeomType
	if err := (&v).Parse(value); err != nil {
		return v, err
	}
	return v, nil
}
