// Code generated by mojo. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"sync"

	"github.com/mojo-lang/mojo/go/pkg/mojo/db"
	"github.com/mojo-lang/mojo/go/pkg/mojo/db/query"
	entity "github.com/ncraft-io/tilestream/go/pkg/tilestream"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var pointTileInstance *PointTile
var pointTileInstanceOnce sync.Once

func GetPointTileModel() *PointTile {
	var err error
	pointTileInstanceOnce.Do(func() {
		pointTileInstance, err = NewPointTile(GetDB())
		if err != nil {
			panic(fmt.Sprintf("failed to create PointTile module %v", err))
		}
	})

	return pointTileInstance
}

type PointTile struct {
	DB        *db.DB
	keyColumn string
}

// NewPointTile uses the service's database connection. Migration is controlled
// by db.Config.DisableAutoMigrate; connection ownership stays with the caller.
func NewPointTile(database *db.DB) (*PointTile, error) {
	column, err := prepareModel(database, &entity.PointTile{}, "Id")
	if err != nil {
		return nil, err
	}
	return &PointTile{DB: database, keyColumn: column}, nil
}

func (m *PointTile) Create(ctx context.Context, value *entity.PointTile) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("PointTile: nil record")
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(value)
	return result.RowsAffected, result.Error
}

func (m *PointTile) Get(ctx context.Context, id string) (*entity.PointTile, error) {
	value := &entity.PointTile{}
	err := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).First(value).Error
	if err != nil {
		return nil, err
	}
	return value, nil
}

func (m *PointTile) Delete(ctx context.Context, id string) (int64, error) {
	result := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).Delete(&entity.PointTile{})
	return result.RowsAffected, result.Error
}

// Update writes non-key fields, not including zero values, without inserting
// a missing record or changing its primary key.
func (m *PointTile) Update(ctx context.Context, value *entity.PointTile, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, m.keyColumn, value.Id, columns...)
}

func (m *PointTile) UpdateBy(ctx context.Context, value *entity.PointTile, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, keyColumn, keyValue, columns...)
}

func (m *PointTile) update(tx *gorm.DB, value *entity.PointTile, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("PointTile: nil record")
	}
	result := tx.Model(&entity.PointTile{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue})

	if len(columns) == 0 {
		result = result.Omit(keyColumn).Updates(value)
	} else {
		result = result.Select(columns).Omit(keyColumn).Updates(value)
	}

	return result.RowsAffected, result.Error
}

// Update writes all non-key fields, including zero values, without inserting
// a missing record or changing its primary key.
func (m *PointTile) UpdateAll(ctx context.Context, value *entity.PointTile) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, m.keyColumn, value.Id)
}

func (m *PointTile) UpdateAllBy(ctx context.Context, value *entity.PointTile, keyColumn string, keyValue interface{}) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, keyColumn, keyValue)
}

func (m *PointTile) updateAll(tx *gorm.DB, value *entity.PointTile, keyColumn string, keyValue interface{}) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("PointTile: nil record")
	}
	result := tx.Model(&entity.PointTile{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue}).
		Select("*").Omit(keyColumn).Updates(value)
	return result.RowsAffected, result.Error
}

func (m *PointTile) List(ctx context.Context, q *query.Query) ([]*entity.PointTile, error) {
	values := make([]*entity.PointTile, 0)
	tx := m.DB.WithContext(ctx).Model(&entity.PointTile{})
	if q != nil {
		if err := q.Normalize(); err != nil {
			return nil, err
		}
		tx = q.Apply(tx, query.Fields{
			"version": {Type: query.FieldTypeInteger, Repeated: false}, "id": {Type: query.FieldTypeString, Repeated: false}, "type": {Type: query.FieldTypeString, Repeated: false}, "keys": {Type: query.FieldTypeString, Repeated: true}, "values": {Type: query.FieldTypeJSON, Repeated: true}, "raw_values": {Type: query.FieldTypeInteger, Repeated: true}, "ids": {Type: query.FieldTypeInteger, Repeated: true}, "tags": {Type: query.FieldTypeInteger, Repeated: true}, "xs": {Type: query.FieldTypeInteger, Repeated: true}, "ys": {Type: query.FieldTypeInteger, Repeated: true},
		})
	}
	if err := tx.Find(&values).Error; err != nil {
		return nil, err
	}
	return values, nil
}

func (m *PointTile) BatchCreate(ctx context.Context, values ...*entity.PointTile) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	for _, value := range values {
		if value == nil {
			return 0, fmt.Errorf("PointTile: nil record")
		}
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(values, len(values))
	return result.RowsAffected, result.Error
}

func (m *PointTile) BatchGet(ctx context.Context, ids ...string) ([]*entity.PointTile, error) {
	values := make([]*entity.PointTile, 0)
	if len(ids) == 0 {
		return values, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	err := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Find(&values).Error
	if err != nil {
		return nil, err
	}
	return values, nil
}

func (m *PointTile) BatchDelete(ctx context.Context, ids ...string) (int64, error) {
	if len(ids) == 0 {
		return 0, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	result := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Delete(&entity.PointTile{})
	return result.RowsAffected, result.Error
}

func (m *PointTile) BatchUpdate(ctx context.Context, values []*entity.PointTile, columns ...string) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.update(tx, value, m.keyColumn, value.Id, columns...)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}

func (m *PointTile) BatchUpdateAll(ctx context.Context, values []*entity.PointTile) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.updateAll(tx, value, m.keyColumn, value.Id)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}
