// Code generated by mojo. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"sync"

	"github.com/mojo-lang/mojo/go/pkg/mojo/db"
	"github.com/mojo-lang/mojo/go/pkg/mojo/db/query"
	entity "github.com/ncraft-io/tilestream/go/pkg/tilestream"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var tileInfoInstance *TileInfo
var tileInfoInstanceOnce sync.Once

func GetTileInfoModel() *TileInfo {
	var err error
	tileInfoInstanceOnce.Do(func() {
		tileInfoInstance, err = NewTileInfo(GetDB())
		if err != nil {
			panic(fmt.Sprintf("failed to create TileInfo module %v", err))
		}
	})

	return tileInfoInstance
}

type TileInfo struct {
	DB        *db.DB
	keyColumn string
}

// NewTileInfo uses the service's database connection. Migration is controlled
// by db.Config.DisableAutoMigrate; connection ownership stays with the caller.
func NewTileInfo(database *db.DB) (*TileInfo, error) {
	column, err := prepareModel(database, &entity.TileInfo{}, "Id")
	if err != nil {
		return nil, err
	}
	return &TileInfo{DB: database, keyColumn: column}, nil
}

func (m *TileInfo) Create(ctx context.Context, value *entity.TileInfo) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("TileInfo: nil record")
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(value)
	return result.RowsAffected, result.Error
}

func (m *TileInfo) Get(ctx context.Context, id string) (*entity.TileInfo, error) {
	value := &entity.TileInfo{}
	err := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).First(value).Error
	if err != nil {
		return nil, err
	}
	return value, nil
}

func (m *TileInfo) Delete(ctx context.Context, id string) (int64, error) {
	result := m.DB.WithContext(ctx).Where(clause.Eq{Column: clause.Column{Name: m.keyColumn}, Value: id}).Delete(&entity.TileInfo{})
	return result.RowsAffected, result.Error
}

// Update writes non-key fields, not including zero values, without inserting
// a missing record or changing its primary key.
func (m *TileInfo) Update(ctx context.Context, value *entity.TileInfo, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, m.keyColumn, value.Id, columns...)
}

func (m *TileInfo) UpdateBy(ctx context.Context, value *entity.TileInfo, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	return m.update(m.DB.WithContext(ctx), value, keyColumn, keyValue, columns...)
}

func (m *TileInfo) update(tx *gorm.DB, value *entity.TileInfo, keyColumn string, keyValue interface{}, columns ...string) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("TileInfo: nil record")
	}
	result := tx.Model(&entity.TileInfo{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue})

	if len(columns) == 0 {
		result = result.Omit(keyColumn).Updates(value)
	} else {
		result = result.Select(columns).Omit(keyColumn).Updates(value)
	}

	return result.RowsAffected, result.Error
}

// Update writes all non-key fields, including zero values, without inserting
// a missing record or changing its primary key.
func (m *TileInfo) UpdateAll(ctx context.Context, value *entity.TileInfo) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, m.keyColumn, value.Id)
}

func (m *TileInfo) UpdateAllBy(ctx context.Context, value *entity.TileInfo, keyColumn string, keyValue interface{}) (int64, error) {
	return m.updateAll(m.DB.WithContext(ctx), value, keyColumn, keyValue)
}

func (m *TileInfo) updateAll(tx *gorm.DB, value *entity.TileInfo, keyColumn string, keyValue interface{}) (int64, error) {
	if value == nil {
		return 0, fmt.Errorf("TileInfo: nil record")
	}
	result := tx.Model(&entity.TileInfo{}).
		Where(clause.Eq{Column: clause.Column{Name: keyColumn}, Value: keyValue}).
		Select("*").Omit(keyColumn).Updates(value)
	return result.RowsAffected, result.Error
}

func (m *TileInfo) List(ctx context.Context, q *query.Query) ([]*entity.TileInfo, error) {
	values := make([]*entity.TileInfo, 0)
	tx := m.DB.WithContext(ctx).Model(&entity.TileInfo{})
	if q != nil {
		if err := q.Normalize(); err != nil {
			return nil, err
		}
		tx = q.Apply(tx, query.Fields{
			"id": {Type: query.FieldTypeString, Repeated: false}, "name": {Type: query.FieldTypeString, Repeated: false}, "type": {Type: query.FieldTypeString, Repeated: false}, "description": {Type: query.FieldTypeString, Repeated: false}, "format": {Type: query.FieldTypeString, Repeated: false}, "version": {Type: query.FieldTypeString, Repeated: false}, "attribution": {Type: query.FieldTypeString, Repeated: false}, "scheme": {Type: query.FieldTypeString, Repeated: false}, "min_zoom": {Type: query.FieldTypeInteger, Repeated: false}, "max_zoom": {Type: query.FieldTypeInteger, Repeated: false}, "bounds": {Type: query.FieldTypeJSON, Repeated: false}, "center": {Type: query.FieldTypeJSON, Repeated: false},
		})
	}
	if err := tx.Find(&values).Error; err != nil {
		return nil, err
	}
	return values, nil
}

func (m *TileInfo) BatchCreate(ctx context.Context, values ...*entity.TileInfo) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	for _, value := range values {
		if value == nil {
			return 0, fmt.Errorf("TileInfo: nil record")
		}
	}
	result := m.DB.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(values, len(values))
	return result.RowsAffected, result.Error
}

func (m *TileInfo) BatchGet(ctx context.Context, ids ...string) ([]*entity.TileInfo, error) {
	values := make([]*entity.TileInfo, 0)
	if len(ids) == 0 {
		return values, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	err := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Find(&values).Error
	if err != nil {
		return nil, err
	}
	return values, nil
}

func (m *TileInfo) BatchDelete(ctx context.Context, ids ...string) (int64, error) {
	if len(ids) == 0 {
		return 0, nil
	}
	keys := make([]interface{}, len(ids))
	for i, id := range ids {
		keys[i] = id
	}
	result := m.DB.WithContext(ctx).Where(clause.IN{Column: clause.Column{Name: m.keyColumn}, Values: keys}).Delete(&entity.TileInfo{})
	return result.RowsAffected, result.Error
}

func (m *TileInfo) BatchUpdate(ctx context.Context, values []*entity.TileInfo, columns ...string) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.update(tx, value, m.keyColumn, value.Id, columns...)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}

func (m *TileInfo) BatchUpdateAll(ctx context.Context, values []*entity.TileInfo) (int64, error) {
	if len(values) == 0 {
		return 0, nil
	}
	var affected int64
	err := m.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, value := range values {
			count, err := m.updateAll(tx, value, m.keyColumn, value.Id)
			if err != nil {
				return err
			}
			affected += count
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return affected, nil
}
