// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/layer.proto

package io.ncraft.tilestream;

public interface LayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.Layer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bool templated = 4;</code>
   * @return The templated.
   */
  boolean getTemplated();

  /**
   * <code>.mojo.core.Object config = 5 [(.mojo.db_json) = true];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.mojo.core.Object config = 5 [(.mojo.db_json) = true];</code>
   * @return The config.
   */
  org.mojolang.mojo.core.Object getConfig();
  /**
   * <code>.mojo.core.Object config = 5 [(.mojo.db_json) = true];</code>
   */
  org.mojolang.mojo.core.ObjectOrBuilder getConfigOrBuilder();

  /**
   * <code>string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   * @return The createTime.
   */
  org.mojolang.mojo.core.Timestamp getCreateTime();
  /**
   * <code>.mojo.core.Timestamp create_time = 100;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   * @return The updateTime.
   */
  org.mojolang.mojo.core.Timestamp getUpdateTime();
  /**
   * <code>.mojo.core.Timestamp update_time = 101;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getUpdateTimeOrBuilder();
}
