// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/point_tile.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream;

public final class PointTileProto {
  private PointTileProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      PointTileProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_PointTile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_PointTile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033tilestream/point_tile.proto\022\ntilestrea" +
      "m\032\034tilestream/vector_tile.proto\"\271\001\n\tPoin" +
      "tTile\022\017\n\007version\030\017 \001(\005\022\n\n\002id\030\001 \001(\t\022\014\n\004ty" +
      "pe\030\002 \001(\t\022\014\n\004keys\030\003 \003(\t\022,\n\006values\030\004 \003(\0132\034" +
      ".tilestream.VectorTile.Value\022\022\n\nraw_valu" +
      "es\030\006 \003(\005\022\013\n\003ids\030\005 \003(\004\022\014\n\004tags\030\n \003(\r\022\n\n\002x" +
      "s\030\013 \003(\005\022\n\n\002ys\030\014 \003(\005Bf\n\024io.ncraft.tilestr" +
      "eamB\016PointTileProtoP\001Z<github.com/ncraft" +
      "-io/tilestream/go/pkg/tilestream;tilestr" +
      "eamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.ncraft.tilestream.VectorTileProto.getDescriptor(),
        });
    internal_static_tilestream_PointTile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_PointTile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_PointTile_descriptor,
        new java.lang.String[] { "Version", "Id", "Type", "Keys", "Values", "RawValues", "Ids", "Tags", "Xs", "Ys", });
    descriptor.resolveAllFeaturesImmutable();
    io.ncraft.tilestream.VectorTileProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
