// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/point_tile.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream;

public interface PointTileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.PointTile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 15;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated string keys = 3;</code>
   * @return A list containing the keys.
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 3;</code>
   * @return The count of keys.
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 3;</code>
   * @param index The index of the element to return.
   * @return The keys at the given index.
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keys at the given index.
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);

  /**
   * <code>repeated .tilestream.VectorTile.Value values = 4;</code>
   */
  java.util.List<io.ncraft.tilestream.VectorTile.Value> 
      getValuesList();
  /**
   * <code>repeated .tilestream.VectorTile.Value values = 4;</code>
   */
  io.ncraft.tilestream.VectorTile.Value getValues(int index);
  /**
   * <code>repeated .tilestream.VectorTile.Value values = 4;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .tilestream.VectorTile.Value values = 4;</code>
   */
  java.util.List<? extends io.ncraft.tilestream.VectorTile.ValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .tilestream.VectorTile.Value values = 4;</code>
   */
  io.ncraft.tilestream.VectorTile.ValueOrBuilder getValuesOrBuilder(
      int index);

  /**
   * <code>repeated int32 raw_values = 6;</code>
   * @return A list containing the rawValues.
   */
  java.util.List<java.lang.Integer> getRawValuesList();
  /**
   * <code>repeated int32 raw_values = 6;</code>
   * @return The count of rawValues.
   */
  int getRawValuesCount();
  /**
   * <code>repeated int32 raw_values = 6;</code>
   * @param index The index of the element to return.
   * @return The rawValues at the given index.
   */
  int getRawValues(int index);

  /**
   * <code>repeated uint64 ids = 5;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated uint64 ids = 5;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated uint64 ids = 5;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  long getIds(int index);

  /**
   * <code>repeated uint32 tags = 10;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.Integer> getTagsList();
  /**
   * <code>repeated uint32 tags = 10;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated uint32 tags = 10;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  int getTags(int index);

  /**
   * <code>repeated int32 xs = 11;</code>
   * @return A list containing the xs.
   */
  java.util.List<java.lang.Integer> getXsList();
  /**
   * <code>repeated int32 xs = 11;</code>
   * @return The count of xs.
   */
  int getXsCount();
  /**
   * <code>repeated int32 xs = 11;</code>
   * @param index The index of the element to return.
   * @return The xs at the given index.
   */
  int getXs(int index);

  /**
   * <code>repeated int32 ys = 12;</code>
   * @return A list containing the ys.
   */
  java.util.List<java.lang.Integer> getYsList();
  /**
   * <code>repeated int32 ys = 12;</code>
   * @return The count of ys.
   */
  int getYsCount();
  /**
   * <code>repeated int32 ys = 12;</code>
   * @param index The index of the element to return.
   * @return The ys at the given index.
   */
  int getYs(int index);
}
