// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/tile.proto

package io.ncraft.tilestream;

public interface TileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.Tile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>string format = 10;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 10;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>string encoding = 11;</code>
   * @return The encoding.
   */
  java.lang.String getEncoding();
  /**
   * <code>string encoding = 11;</code>
   * @return The bytes for encoding.
   */
  com.google.protobuf.ByteString
      getEncodingBytes();

  /**
   * <code>bytes content = 15;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
