// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/tile_info.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream;

public final class TileInfoProto {
  private TileInfoProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TileInfoProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_TileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_TileInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032tilestream/tile_info.proto\022\ntilestream" +
      "\032\034mojo/geom/bounding_box.proto\032\027mojo/geo" +
      "m/lng_lat.proto\"\374\001\n\010TileInfo\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\023\n\013descript" +
      "ion\030\004 \001(\t\022\016\n\006format\030\005 \001(\t\022\017\n\007version\030\006 \001" +
      "(\t\022\023\n\013attribution\030\007 \001(\t\022\016\n\006scheme\030\010 \001(\t\022" +
      "\020\n\010min_zoom\030\n \001(\005\022\020\n\010max_zoom\030\013 \001(\005\022&\n\006b" +
      "ounds\030\016 \001(\0132\026.mojo.geom.BoundingBox\022!\n\006c" +
      "enter\030\017 \001(\0132\021.mojo.geom.LngLatBe\n\024io.ncr" +
      "aft.tilestreamB\rTileInfoProtoP\001Z<github." +
      "com/ncraft-io/tilestream/go/pkg/tilestre" +
      "am;tilestreamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.BoundingBoxProto.getDescriptor(),
          org.mojolang.mojo.geom.LngLatProto.getDescriptor(),
        });
    internal_static_tilestream_TileInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_TileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_TileInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", "Description", "Format", "Version", "Attribution", "Scheme", "MinZoom", "MaxZoom", "Bounds", "Center", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.geom.BoundingBoxProto.getDescriptor();
    org.mojolang.mojo.geom.LngLatProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
