// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/tile_id.proto

package io.ncraft.tilestream;

public interface TileIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.TileId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();
}
