// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/tile_id.proto

package io.ncraft.tilestream;

public final class TileIdProto {
  private TileIdProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_TileId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tilestream_TileId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030tilestream/tile_id.proto\022\ntilestream\"-" +
      "\n\006TileId\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\r\n\005level\030" +
      "\003 \001(\005Bc\n\024io.ncraft.tilestreamB\013TileIdPro" +
      "toP\001Z<github.com/ncraft-io/tilestream/go" +
      "/pkg/tilestream;tilestreamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tilestream_TileId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_TileId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tilestream_TileId_descriptor,
        new java.lang.String[] { "X", "Y", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
