// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/tile.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream;

public final class TileProto {
  private TileProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TileProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_Tile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_Tile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025tilestream/tile.proto\022\ntilestream\"^\n\004T" +
      "ile\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\r\n\005level\030\003 \001(\005" +
      "\022\016\n\006format\030\n \001(\t\022\020\n\010encoding\030\013 \001(\t\022\017\n\007co" +
      "ntent\030\017 \001(\014Ba\n\024io.ncraft.tilestreamB\tTil" +
      "eProtoP\001Z<github.com/ncraft-io/tilestrea" +
      "m/go/pkg/tilestream;tilestreamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tilestream_Tile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_Tile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_Tile_descriptor,
        new java.lang.String[] { "X", "Y", "Level", "Format", "Encoding", "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
