// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/tile_info.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream;

/**
 * Protobuf type {@code tilestream.TileInfo}
 */
public final class TileInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tilestream.TileInfo)
    TileInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TileInfo.class.getName());
  }
  // Use TileInfo.newBuilder() to construct.
  private TileInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TileInfo() {
    id_ = "";
    name_ = "";
    type_ = "";
    description_ = "";
    format_ = "";
    version_ = "";
    attribution_ = "";
    scheme_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.tilestream.TileInfoProto.internal_static_tilestream_TileInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.tilestream.TileInfoProto.internal_static_tilestream_TileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.tilestream.TileInfo.class, io.ncraft.tilestream.TileInfo.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORMAT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object format_ = "";
  /**
   * <code>string format = 5;</code>
   * @return The format.
   */
  @java.lang.Override
  public java.lang.String getFormat() {
    java.lang.Object ref = format_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      format_ = s;
      return s;
    }
  }
  /**
   * <code>string format = 5;</code>
   * @return The bytes for format.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormatBytes() {
    java.lang.Object ref = format_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      format_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 6;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 6;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object attribution_ = "";
  /**
   * <code>string attribution = 7;</code>
   * @return The attribution.
   */
  @java.lang.Override
  public java.lang.String getAttribution() {
    java.lang.Object ref = attribution_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      attribution_ = s;
      return s;
    }
  }
  /**
   * <code>string attribution = 7;</code>
   * @return The bytes for attribution.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAttributionBytes() {
    java.lang.Object ref = attribution_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      attribution_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scheme_ = "";
  /**
   * <code>string scheme = 8;</code>
   * @return The scheme.
   */
  @java.lang.Override
  public java.lang.String getScheme() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scheme_ = s;
      return s;
    }
  }
  /**
   * <code>string scheme = 8;</code>
   * @return The bytes for scheme.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemeBytes() {
    java.lang.Object ref = scheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIN_ZOOM_FIELD_NUMBER = 10;
  private int minZoom_ = 0;
  /**
   * <code>int32 min_zoom = 10;</code>
   * @return The minZoom.
   */
  @java.lang.Override
  public int getMinZoom() {
    return minZoom_;
  }

  public static final int MAX_ZOOM_FIELD_NUMBER = 11;
  private int maxZoom_ = 0;
  /**
   * <code>int32 max_zoom = 11;</code>
   * @return The maxZoom.
   */
  @java.lang.Override
  public int getMaxZoom() {
    return maxZoom_;
  }

  public static final int BOUNDS_FIELD_NUMBER = 14;
  private org.mojolang.mojo.geom.BoundingBox bounds_;
  /**
   * <code>.mojo.geom.BoundingBox bounds = 14;</code>
   * @return Whether the bounds field is set.
   */
  @java.lang.Override
  public boolean hasBounds() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mojo.geom.BoundingBox bounds = 14;</code>
   * @return The bounds.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.BoundingBox getBounds() {
    return bounds_ == null ? org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bounds_;
  }
  /**
   * <code>.mojo.geom.BoundingBox bounds = 14;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.BoundingBoxOrBuilder getBoundsOrBuilder() {
    return bounds_ == null ? org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bounds_;
  }

  public static final int CENTER_FIELD_NUMBER = 15;
  private org.mojolang.mojo.geom.LngLat center_;
  /**
   * <code>.mojo.geom.LngLat center = 15;</code>
   * @return Whether the center field is set.
   */
  @java.lang.Override
  public boolean hasCenter() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.mojo.geom.LngLat center = 15;</code>
   * @return The center.
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLat getCenter() {
    return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
  }
  /**
   * <code>.mojo.geom.LngLat center = 15;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.geom.LngLatOrBuilder getCenterOrBuilder() {
    return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(format_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, format_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attribution_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, attribution_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, scheme_);
    }
    if (minZoom_ != 0) {
      output.writeInt32(10, minZoom_);
    }
    if (maxZoom_ != 0) {
      output.writeInt32(11, maxZoom_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(14, getBounds());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(15, getCenter());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(format_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, format_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, version_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(attribution_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, attribution_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scheme_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, scheme_);
    }
    if (minZoom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, minZoom_);
    }
    if (maxZoom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, maxZoom_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getBounds());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getCenter());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.tilestream.TileInfo)) {
      return super.equals(obj);
    }
    io.ncraft.tilestream.TileInfo other = (io.ncraft.tilestream.TileInfo) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getFormat()
        .equals(other.getFormat())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getAttribution()
        .equals(other.getAttribution())) return false;
    if (!getScheme()
        .equals(other.getScheme())) return false;
    if (getMinZoom()
        != other.getMinZoom()) return false;
    if (getMaxZoom()
        != other.getMaxZoom()) return false;
    if (hasBounds() != other.hasBounds()) return false;
    if (hasBounds()) {
      if (!getBounds()
          .equals(other.getBounds())) return false;
    }
    if (hasCenter() != other.hasCenter()) return false;
    if (hasCenter()) {
      if (!getCenter()
          .equals(other.getCenter())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getFormat().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + ATTRIBUTION_FIELD_NUMBER;
    hash = (53 * hash) + getAttribution().hashCode();
    hash = (37 * hash) + SCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getScheme().hashCode();
    hash = (37 * hash) + MIN_ZOOM_FIELD_NUMBER;
    hash = (53 * hash) + getMinZoom();
    hash = (37 * hash) + MAX_ZOOM_FIELD_NUMBER;
    hash = (53 * hash) + getMaxZoom();
    if (hasBounds()) {
      hash = (37 * hash) + BOUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getBounds().hashCode();
    }
    if (hasCenter()) {
      hash = (37 * hash) + CENTER_FIELD_NUMBER;
      hash = (53 * hash) + getCenter().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.tilestream.TileInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.ncraft.tilestream.TileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.ncraft.tilestream.TileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.tilestream.TileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.tilestream.TileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tilestream.TileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tilestream.TileInfo)
      io.ncraft.tilestream.TileInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.tilestream.TileInfoProto.internal_static_tilestream_TileInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.tilestream.TileInfoProto.internal_static_tilestream_TileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.tilestream.TileInfo.class, io.ncraft.tilestream.TileInfo.Builder.class);
    }

    // Construct using io.ncraft.tilestream.TileInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBoundsFieldBuilder();
        getCenterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      type_ = "";
      description_ = "";
      format_ = "";
      version_ = "";
      attribution_ = "";
      scheme_ = "";
      minZoom_ = 0;
      maxZoom_ = 0;
      bounds_ = null;
      if (boundsBuilder_ != null) {
        boundsBuilder_.dispose();
        boundsBuilder_ = null;
      }
      center_ = null;
      if (centerBuilder_ != null) {
        centerBuilder_.dispose();
        centerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.tilestream.TileInfoProto.internal_static_tilestream_TileInfo_descriptor;
    }

    @java.lang.Override
    public io.ncraft.tilestream.TileInfo getDefaultInstanceForType() {
      return io.ncraft.tilestream.TileInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.tilestream.TileInfo build() {
      io.ncraft.tilestream.TileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.tilestream.TileInfo buildPartial() {
      io.ncraft.tilestream.TileInfo result = new io.ncraft.tilestream.TileInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.ncraft.tilestream.TileInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.format_ = format_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.attribution_ = attribution_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.scheme_ = scheme_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.minZoom_ = minZoom_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.maxZoom_ = maxZoom_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.bounds_ = boundsBuilder_ == null
            ? bounds_
            : boundsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.center_ = centerBuilder_ == null
            ? center_
            : centerBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.tilestream.TileInfo) {
        return mergeFrom((io.ncraft.tilestream.TileInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.tilestream.TileInfo other) {
      if (other == io.ncraft.tilestream.TileInfo.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getFormat().isEmpty()) {
        format_ = other.format_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getAttribution().isEmpty()) {
        attribution_ = other.attribution_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getScheme().isEmpty()) {
        scheme_ = other.scheme_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getMinZoom() != 0) {
        setMinZoom(other.getMinZoom());
      }
      if (other.getMaxZoom() != 0) {
        setMaxZoom(other.getMaxZoom());
      }
      if (other.hasBounds()) {
        mergeBounds(other.getBounds());
      }
      if (other.hasCenter()) {
        mergeCenter(other.getCenter());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              format_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              attribution_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              scheme_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 80: {
              minZoom_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 80
            case 88: {
              maxZoom_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 88
            case 114: {
              input.readMessage(
                  getBoundsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 114
            case 122: {
              input.readMessage(
                  getCenterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object format_ = "";
    /**
     * <code>string format = 5;</code>
     * @return The format.
     */
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        format_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string format = 5;</code>
     * @return The bytes for format.
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string format = 5;</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      format_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string format = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      format_ = getDefaultInstance().getFormat();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string format = 5;</code>
     * @param value The bytes for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      format_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 6;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 6;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object attribution_ = "";
    /**
     * <code>string attribution = 7;</code>
     * @return The attribution.
     */
    public java.lang.String getAttribution() {
      java.lang.Object ref = attribution_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attribution_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string attribution = 7;</code>
     * @return The bytes for attribution.
     */
    public com.google.protobuf.ByteString
        getAttributionBytes() {
      java.lang.Object ref = attribution_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attribution_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string attribution = 7;</code>
     * @param value The attribution to set.
     * @return This builder for chaining.
     */
    public Builder setAttribution(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      attribution_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string attribution = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttribution() {
      attribution_ = getDefaultInstance().getAttribution();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string attribution = 7;</code>
     * @param value The bytes for attribution to set.
     * @return This builder for chaining.
     */
    public Builder setAttributionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      attribution_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object scheme_ = "";
    /**
     * <code>string scheme = 8;</code>
     * @return The scheme.
     */
    public java.lang.String getScheme() {
      java.lang.Object ref = scheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scheme = 8;</code>
     * @return The bytes for scheme.
     */
    public com.google.protobuf.ByteString
        getSchemeBytes() {
      java.lang.Object ref = scheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scheme = 8;</code>
     * @param value The scheme to set.
     * @return This builder for chaining.
     */
    public Builder setScheme(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scheme_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearScheme() {
      scheme_ = getDefaultInstance().getScheme();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string scheme = 8;</code>
     * @param value The bytes for scheme to set.
     * @return This builder for chaining.
     */
    public Builder setSchemeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scheme_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int minZoom_ ;
    /**
     * <code>int32 min_zoom = 10;</code>
     * @return The minZoom.
     */
    @java.lang.Override
    public int getMinZoom() {
      return minZoom_;
    }
    /**
     * <code>int32 min_zoom = 10;</code>
     * @param value The minZoom to set.
     * @return This builder for chaining.
     */
    public Builder setMinZoom(int value) {

      minZoom_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 min_zoom = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinZoom() {
      bitField0_ = (bitField0_ & ~0x00000100);
      minZoom_ = 0;
      onChanged();
      return this;
    }

    private int maxZoom_ ;
    /**
     * <code>int32 max_zoom = 11;</code>
     * @return The maxZoom.
     */
    @java.lang.Override
    public int getMaxZoom() {
      return maxZoom_;
    }
    /**
     * <code>int32 max_zoom = 11;</code>
     * @param value The maxZoom to set.
     * @return This builder for chaining.
     */
    public Builder setMaxZoom(int value) {

      maxZoom_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_zoom = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxZoom() {
      bitField0_ = (bitField0_ & ~0x00000200);
      maxZoom_ = 0;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.geom.BoundingBox bounds_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder> boundsBuilder_;
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     * @return Whether the bounds field is set.
     */
    public boolean hasBounds() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     * @return The bounds.
     */
    public org.mojolang.mojo.geom.BoundingBox getBounds() {
      if (boundsBuilder_ == null) {
        return bounds_ == null ? org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bounds_;
      } else {
        return boundsBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public Builder setBounds(org.mojolang.mojo.geom.BoundingBox value) {
      if (boundsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bounds_ = value;
      } else {
        boundsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public Builder setBounds(
        org.mojolang.mojo.geom.BoundingBox.Builder builderForValue) {
      if (boundsBuilder_ == null) {
        bounds_ = builderForValue.build();
      } else {
        boundsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public Builder mergeBounds(org.mojolang.mojo.geom.BoundingBox value) {
      if (boundsBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          bounds_ != null &&
          bounds_ != org.mojolang.mojo.geom.BoundingBox.getDefaultInstance()) {
          getBoundsBuilder().mergeFrom(value);
        } else {
          bounds_ = value;
        }
      } else {
        boundsBuilder_.mergeFrom(value);
      }
      if (bounds_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public Builder clearBounds() {
      bitField0_ = (bitField0_ & ~0x00000400);
      bounds_ = null;
      if (boundsBuilder_ != null) {
        boundsBuilder_.dispose();
        boundsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public org.mojolang.mojo.geom.BoundingBox.Builder getBoundsBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getBoundsFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    public org.mojolang.mojo.geom.BoundingBoxOrBuilder getBoundsOrBuilder() {
      if (boundsBuilder_ != null) {
        return boundsBuilder_.getMessageOrBuilder();
      } else {
        return bounds_ == null ?
            org.mojolang.mojo.geom.BoundingBox.getDefaultInstance() : bounds_;
      }
    }
    /**
     * <code>.mojo.geom.BoundingBox bounds = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder> 
        getBoundsFieldBuilder() {
      if (boundsBuilder_ == null) {
        boundsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.geom.BoundingBox, org.mojolang.mojo.geom.BoundingBox.Builder, org.mojolang.mojo.geom.BoundingBoxOrBuilder>(
                getBounds(),
                getParentForChildren(),
                isClean());
        bounds_ = null;
      }
      return boundsBuilder_;
    }

    private org.mojolang.mojo.geom.LngLat center_;
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> centerBuilder_;
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     * @return Whether the center field is set.
     */
    public boolean hasCenter() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     * @return The center.
     */
    public org.mojolang.mojo.geom.LngLat getCenter() {
      if (centerBuilder_ == null) {
        return center_ == null ? org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
      } else {
        return centerBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public Builder setCenter(org.mojolang.mojo.geom.LngLat value) {
      if (centerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        center_ = value;
      } else {
        centerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public Builder setCenter(
        org.mojolang.mojo.geom.LngLat.Builder builderForValue) {
      if (centerBuilder_ == null) {
        center_ = builderForValue.build();
      } else {
        centerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public Builder mergeCenter(org.mojolang.mojo.geom.LngLat value) {
      if (centerBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          center_ != null &&
          center_ != org.mojolang.mojo.geom.LngLat.getDefaultInstance()) {
          getCenterBuilder().mergeFrom(value);
        } else {
          center_ = value;
        }
      } else {
        centerBuilder_.mergeFrom(value);
      }
      if (center_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public Builder clearCenter() {
      bitField0_ = (bitField0_ & ~0x00000800);
      center_ = null;
      if (centerBuilder_ != null) {
        centerBuilder_.dispose();
        centerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public org.mojolang.mojo.geom.LngLat.Builder getCenterBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getCenterFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    public org.mojolang.mojo.geom.LngLatOrBuilder getCenterOrBuilder() {
      if (centerBuilder_ != null) {
        return centerBuilder_.getMessageOrBuilder();
      } else {
        return center_ == null ?
            org.mojolang.mojo.geom.LngLat.getDefaultInstance() : center_;
      }
    }
    /**
     * <code>.mojo.geom.LngLat center = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder> 
        getCenterFieldBuilder() {
      if (centerBuilder_ == null) {
        centerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.mojolang.mojo.geom.LngLat, org.mojolang.mojo.geom.LngLat.Builder, org.mojolang.mojo.geom.LngLatOrBuilder>(
                getCenter(),
                getParentForChildren(),
                isClean());
        center_ = null;
      }
      return centerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tilestream.TileInfo)
  }

  // @@protoc_insertion_point(class_scope:tilestream.TileInfo)
  private static final io.ncraft.tilestream.TileInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.tilestream.TileInfo();
  }

  public static io.ncraft.tilestream.TileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TileInfo>
      PARSER = new com.google.protobuf.AbstractParser<TileInfo>() {
    @java.lang.Override
    public TileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TileInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TileInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.tilestream.TileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

