// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tilestream/vector_tile.proto

package io.ncraft.tilestream;

public interface VectorTileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.VectorTile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tilestream.VectorTile.Layer layers = 3;</code>
   */
  java.util.List<io.ncraft.tilestream.VectorTile.Layer> 
      getLayersList();
  /**
   * <code>repeated .tilestream.VectorTile.Layer layers = 3;</code>
   */
  io.ncraft.tilestream.VectorTile.Layer getLayers(int index);
  /**
   * <code>repeated .tilestream.VectorTile.Layer layers = 3;</code>
   */
  int getLayersCount();
  /**
   * <code>repeated .tilestream.VectorTile.Layer layers = 3;</code>
   */
  java.util.List<? extends io.ncraft.tilestream.VectorTile.LayerOrBuilder> 
      getLayersOrBuilderList();
  /**
   * <code>repeated .tilestream.VectorTile.Layer layers = 3;</code>
   */
  io.ncraft.tilestream.VectorTile.LayerOrBuilder getLayersOrBuilder(
      int index);
}
