// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/providers/postgis/config.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.providers.postgis;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tilestream.providers.postgis.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool debug = 1;</code>
   * @return The debug.
   */
  boolean getDebug();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 min_zoom = 4;</code>
   * @return The minZoom.
   */
  long getMinZoom();

  /**
   * <code>int64 max_zoom = 5;</code>
   * @return The maxZoom.
   */
  long getMaxZoom();

  /**
   * <code>.mojo.geom.BoundingBox bounds = 6;</code>
   * @return Whether the bounds field is set.
   */
  boolean hasBounds();
  /**
   * <code>.mojo.geom.BoundingBox bounds = 6;</code>
   * @return The bounds.
   */
  org.mojolang.mojo.geom.BoundingBox getBounds();
  /**
   * <code>.mojo.geom.BoundingBox bounds = 6;</code>
   */
  org.mojolang.mojo.geom.BoundingBoxOrBuilder getBoundsOrBuilder();

  /**
   * <code>int64 tile_buffer = 7;</code>
   * @return The tileBuffer.
   */
  long getTileBuffer();

  /**
   * <code>.tilestream.providers.postgis.Config.Provider provider = 10;</code>
   * @return Whether the provider field is set.
   */
  boolean hasProvider();
  /**
   * <code>.tilestream.providers.postgis.Config.Provider provider = 10;</code>
   * @return The provider.
   */
  io.ncraft.tilestream.providers.postgis.Config.Provider getProvider();
  /**
   * <code>.tilestream.providers.postgis.Config.Provider provider = 10;</code>
   */
  io.ncraft.tilestream.providers.postgis.Config.ProviderOrBuilder getProviderOrBuilder();
}
