// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tilestream/providers/postgis/config.proto
// Protobuf Java Version: 4.29.2

package io.ncraft.tilestream.providers.postgis;

public final class ConfigProto {
  private ConfigProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      ConfigProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_providers_postgis_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_providers_postgis_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_providers_postgis_Config_Sql_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_providers_postgis_Config_Sql_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_providers_postgis_Config_Sql_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_providers_postgis_Config_Sql_Field_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tilestream_providers_postgis_Config_Provider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tilestream_providers_postgis_Config_Provider_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)tilestream/providers/postgis/config.pr" +
      "oto\022\034tilestream.providers.postgis\032\034mojo/" +
      "geom/bounding_box.proto\"\316\003\n\006Config\022\r\n\005de" +
      "bug\030\001 \001(\010\022\014\n\004name\030\002 \001(\t\022\020\n\010min_zoom\030\004 \001(" +
      "\003\022\020\n\010max_zoom\030\005 \001(\003\022&\n\006bounds\030\006 \001(\0132\026.mo" +
      "jo.geom.BoundingBox\022\023\n\013tile_buffer\030\007 \001(\003" +
      "\022?\n\010provider\030\n \001(\0132-.tilestream.provider" +
      "s.postgis.Config.Provider\032\212\001\n\003Sql\022\r\n\005tab" +
      "le\030\001 \001(\t\022>\n\006fields\030\002 \003(\0132..tilestream.pr" +
      "oviders.postgis.Config.Sql.Field\022\016\n\006filt" +
      "er\030\003 \001(\t\032$\n\005Field\022\014\n\004name\030\001 \001(\t\022\r\n\005alias" +
      "\030\002 \001(\t\032x\n\010Provider\022\013\n\003uri\030\001 \001(\t\022\020\n\010id_fi" +
      "eld\030\002 \001(\t\022\026\n\016geometry_field\030\003 \001(\t\0225\n\003sql" +
      "\030\004 \001(\0132(.tilestream.providers.postgis.Co" +
      "nfig.SqlB\204\001\n&io.ncraft.tilestream.provid" +
      "ers.postgisB\013ConfigProtoP\001ZKgithub.com/n" +
      "craft-io/tilestream/go/pkg/tilestream/pr" +
      "oviders/postgis;postgisb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.geom.BoundingBoxProto.getDescriptor(),
        });
    internal_static_tilestream_providers_postgis_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tilestream_providers_postgis_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_providers_postgis_Config_descriptor,
        new java.lang.String[] { "Debug", "Name", "MinZoom", "MaxZoom", "Bounds", "TileBuffer", "Provider", });
    internal_static_tilestream_providers_postgis_Config_Sql_descriptor =
      internal_static_tilestream_providers_postgis_Config_descriptor.getNestedTypes().get(0);
    internal_static_tilestream_providers_postgis_Config_Sql_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_providers_postgis_Config_Sql_descriptor,
        new java.lang.String[] { "Table", "Fields", "Filter", });
    internal_static_tilestream_providers_postgis_Config_Sql_Field_descriptor =
      internal_static_tilestream_providers_postgis_Config_Sql_descriptor.getNestedTypes().get(0);
    internal_static_tilestream_providers_postgis_Config_Sql_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_providers_postgis_Config_Sql_Field_descriptor,
        new java.lang.String[] { "Name", "Alias", });
    internal_static_tilestream_providers_postgis_Config_Provider_descriptor =
      internal_static_tilestream_providers_postgis_Config_descriptor.getNestedTypes().get(1);
    internal_static_tilestream_providers_postgis_Config_Provider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tilestream_providers_postgis_Config_Provider_descriptor,
        new java.lang.String[] { "Uri", "IdField", "GeometryField", "Sql", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.geom.BoundingBoxProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
