// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.2
// source: tilestream/providers/postgis/config.proto

package postgis

import (
	geom "github.com/mojo-lang/mojo/go/pkg/mojo/geom"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug      bool              `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	Name       string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinZoom    int64             `protobuf:"varint,4,opt,name=min_zoom,json=minZoom,proto3" json:"minZoom,omitempty"`
	MaxZoom    int64             `protobuf:"varint,5,opt,name=max_zoom,json=maxZoom,proto3" json:"maxZoom,omitempty"`
	Bounds     *geom.BoundingBox `protobuf:"bytes,6,opt,name=bounds,proto3" json:"bounds,omitempty"`
	TileBuffer int64             `protobuf:"varint,7,opt,name=tile_buffer,json=tileBuffer,proto3" json:"tileBuffer,omitempty"`
	Provider   *Config_Provider  `protobuf:"bytes,10,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tilestream_providers_postgis_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_tilestream_providers_postgis_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_tilestream_providers_postgis_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetMinZoom() int64 {
	if x != nil {
		return x.MinZoom
	}
	return 0
}

func (x *Config) GetMaxZoom() int64 {
	if x != nil {
		return x.MaxZoom
	}
	return 0
}

func (x *Config) GetBounds() *geom.BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Config) GetTileBuffer() int64 {
	if x != nil {
		return x.TileBuffer
	}
	return 0
}

func (x *Config) GetProvider() *Config_Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type Config_Sql struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Fields []*Config_Sql_Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter string              `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *Config_Sql) Reset() {
	*x = Config_Sql{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tilestream_providers_postgis_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Sql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Sql) ProtoMessage() {}

func (x *Config_Sql) ProtoReflect() protoreflect.Message {
	mi := &file_tilestream_providers_postgis_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Sql.ProtoReflect.Descriptor instead.
func (*Config_Sql) Descriptor() ([]byte, []int) {
	return file_tilestream_providers_postgis_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_Sql) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Config_Sql) GetFields() []*Config_Sql_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Config_Sql) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type Config_Provider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri           string      `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	IdField       string      `protobuf:"bytes,2,opt,name=id_field,json=idField,proto3" json:"idField,omitempty"`
	GeometryField string      `protobuf:"bytes,3,opt,name=geometry_field,json=geometryField,proto3" json:"geometryField,omitempty"`
	Sql           *Config_Sql `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *Config_Provider) Reset() {
	*x = Config_Provider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tilestream_providers_postgis_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Provider) ProtoMessage() {}

func (x *Config_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_tilestream_providers_postgis_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Provider.ProtoReflect.Descriptor instead.
func (*Config_Provider) Descriptor() ([]byte, []int) {
	return file_tilestream_providers_postgis_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Config_Provider) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Config_Provider) GetIdField() string {
	if x != nil {
		return x.IdField
	}
	return ""
}

func (x *Config_Provider) GetGeometryField() string {
	if x != nil {
		return x.GeometryField
	}
	return ""
}

func (x *Config_Provider) GetSql() *Config_Sql {
	if x != nil {
		return x.Sql
	}
	return nil
}

type Config_Sql_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *Config_Sql_Field) Reset() {
	*x = Config_Sql_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tilestream_providers_postgis_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Sql_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Sql_Field) ProtoMessage() {}

func (x *Config_Sql_Field) ProtoReflect() protoreflect.Message {
	mi := &file_tilestream_providers_postgis_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Sql_Field.ProtoReflect.Descriptor instead.
func (*Config_Sql_Field) Descriptor() ([]byte, []int) {
	return file_tilestream_providers_postgis_config_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Config_Sql_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_Sql_Field) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

var File_tilestream_providers_postgis_config_proto protoreflect.FileDescriptor

var file_tilestream_providers_postgis_config_proto_rawDesc = []byte{
	0x0a, 0x29, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x74, 0x69, 0x6c,
	0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x1a, 0x1c, 0x6d, 0x6f, 0x6a, 0x6f, 0x2f,
	0x67, 0x65, 0x6f, 0x6d, 0x2f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x62, 0x6f,
	0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x04, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x69, 0x6e, 0x5f, 0x7a, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6d, 0x69, 0x6e, 0x5a, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x7a,
	0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x5a, 0x6f,
	0x6f, 0x6d, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x2e, 0x42,
	0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x69, 0x6c, 0x65, 0x42, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x67, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x1a, 0xae,
	0x01, 0x0a, 0x03, 0x53, 0x71, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x53, 0x71, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x31, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x1a,
	0x9a, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x67, 0x65, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x3a, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x74, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x53, 0x71, 0x6c, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x42, 0x84, 0x01, 0x0a,
	0x26, 0x69, 0x6f, 0x2e, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x42, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2d, 0x69, 0x6f, 0x2f, 0x74, 0x69, 0x6c,
	0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x69, 0x73, 0x3b, 0x70, 0x6f, 0x73, 0x74,
	0x67, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tilestream_providers_postgis_config_proto_rawDescOnce sync.Once
	file_tilestream_providers_postgis_config_proto_rawDescData = file_tilestream_providers_postgis_config_proto_rawDesc
)

func file_tilestream_providers_postgis_config_proto_rawDescGZIP() []byte {
	file_tilestream_providers_postgis_config_proto_rawDescOnce.Do(func() {
		file_tilestream_providers_postgis_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_tilestream_providers_postgis_config_proto_rawDescData)
	})
	return file_tilestream_providers_postgis_config_proto_rawDescData
}

var file_tilestream_providers_postgis_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tilestream_providers_postgis_config_proto_goTypes = []interface{}{
	(*Config)(nil),           // 0: tilestream.providers.postgis.Config
	(*Config_Sql)(nil),       // 1: tilestream.providers.postgis.Config.Sql
	(*Config_Provider)(nil),  // 2: tilestream.providers.postgis.Config.Provider
	(*Config_Sql_Field)(nil), // 3: tilestream.providers.postgis.Config.Sql.Field
	(*geom.BoundingBox)(nil), // 4: mojo.geom.BoundingBox
}
var file_tilestream_providers_postgis_config_proto_depIdxs = []int32{
	4, // 0: tilestream.providers.postgis.Config.bounds:type_name -> mojo.geom.BoundingBox
	2, // 1: tilestream.providers.postgis.Config.provider:type_name -> tilestream.providers.postgis.Config.Provider
	3, // 2: tilestream.providers.postgis.Config.Sql.fields:type_name -> tilestream.providers.postgis.Config.Sql.Field
	1, // 3: tilestream.providers.postgis.Config.Provider.sql:type_name -> tilestream.providers.postgis.Config.Sql
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tilestream_providers_postgis_config_proto_init() }
func file_tilestream_providers_postgis_config_proto_init() {
	if File_tilestream_providers_postgis_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tilestream_providers_postgis_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tilestream_providers_postgis_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Sql); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tilestream_providers_postgis_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Provider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tilestream_providers_postgis_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Sql_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tilestream_providers_postgis_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilestream_providers_postgis_config_proto_goTypes,
		DependencyIndexes: file_tilestream_providers_postgis_config_proto_depIdxs,
		MessageInfos:      file_tilestream_providers_postgis_config_proto_msgTypes,
	}.Build()
	File_tilestream_providers_postgis_config_proto = out.File
	file_tilestream_providers_postgis_config_proto_rawDesc = nil
	file_tilestream_providers_postgis_config_proto_goTypes = nil
	file_tilestream_providers_postgis_config_proto_depIdxs = nil
}
