// Code generated by mojo. DO NOT EDIT.

package tilestream_client

import (
	"context"
	"fmt"
	"github.com/go-kit/kit/endpoint"
	core "github.com/mojo-lang/mojo/go/pkg/mojo/core"
	tilestream "github.com/ncraft-io/tilestream/go/pkg/tilestream"
	pb "github.com/ncraft-io/tilestream/go/pkg/tilestream/v1"
)

// Client is the transport-independent unary API implemented by HTTP and gRPC clients.
type Client interface {
	CreateTile(context.Context, *pb.CreateTileRequest) (*tilestream.Tile, error)
	BatchCreateTiles(context.Context, *pb.BatchCreateTilesRequest) (*core.Null, error)
	CreateTiles(context.Context, *pb.CreateTilesRequest) (*core.Null, error)
	GetTile(context.Context, *pb.GetTileRequest) (*tilestream.Tile, error)
	GetTileInfo(context.Context, *pb.GetTileInfoRequest) (*tilestream.TileInfo, error)
	UpdateTile(context.Context, *pb.UpdateTileRequest) (*core.Null, error)
	UpdateTileInfo(context.Context, *pb.UpdateTileInfoRequest) (*core.Null, error)
	CreateLayer(context.Context, *pb.CreateLayerRequest) (*tilestream.Layer, error)
	BatchCreateLayer(context.Context, *pb.BatchCreateLayerRequest) (*pb.BatchCreateLayerResponse, error)
	UpdateLayer(context.Context, *pb.UpdateLayerRequest) (*core.Null, error)
	BatchUpdateLayer(context.Context, *pb.BatchUpdateLayerRequest) (*core.Null, error)
	DeleteLayer(context.Context, *pb.DeleteLayerRequest) (*core.Null, error)
	GetLayer(context.Context, *pb.GetLayerRequest) (*tilestream.Layer, error)
	BatchGetLayers(context.Context, *pb.BatchGetLayersRequest) (*pb.BatchGetLayersResponse, error)
	ListLayers(context.Context, *pb.ListLayersRequest) (*pb.ListLayersResponse, error)
}

type Endpoints struct {
	CreateTileEndpoint       endpoint.Endpoint
	BatchCreateTilesEndpoint endpoint.Endpoint
	CreateTilesEndpoint      endpoint.Endpoint
	GetTileEndpoint          endpoint.Endpoint
	GetTileInfoEndpoint      endpoint.Endpoint
	UpdateTileEndpoint       endpoint.Endpoint
	UpdateTileInfoEndpoint   endpoint.Endpoint
	CreateLayerEndpoint      endpoint.Endpoint
	BatchCreateLayerEndpoint endpoint.Endpoint
	UpdateLayerEndpoint      endpoint.Endpoint
	BatchUpdateLayerEndpoint endpoint.Endpoint
	DeleteLayerEndpoint      endpoint.Endpoint
	GetLayerEndpoint         endpoint.Endpoint
	BatchGetLayersEndpoint   endpoint.Endpoint
	ListLayersEndpoint       endpoint.Endpoint
}

var _ Client = Endpoints{}
var _ = fmt.Errorf
var _ context.Context
var _ endpoint.Endpoint

func (e Endpoints) CreateTile(ctx context.Context, request *pb.CreateTileRequest) (*tilestream.Tile, error) {
	if request == nil {
		return nil, fmt.Errorf("CreateTile: nil request")
	}
	if e.CreateTileEndpoint == nil {
		return nil, fmt.Errorf("CreateTile: endpoint is not configured")
	}
	result, err := e.CreateTileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*tilestream.Tile)
	if !ok || response == nil {
		return nil, fmt.Errorf("CreateTile: invalid response type %T", result)
	}
	return response, nil
}

func MakeCreateTileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateTile: invalid request type %T", request)
		}
		return client.CreateTile(ctx, req)
	}
}

func (e Endpoints) BatchCreateTiles(ctx context.Context, request *pb.BatchCreateTilesRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("BatchCreateTiles: nil request")
	}
	if e.BatchCreateTilesEndpoint == nil {
		return nil, fmt.Errorf("BatchCreateTiles: endpoint is not configured")
	}
	result, err := e.BatchCreateTilesEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("BatchCreateTiles: invalid response type %T", result)
	}
	return response, nil
}

func MakeBatchCreateTilesEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchCreateTilesRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchCreateTiles: invalid request type %T", request)
		}
		return client.BatchCreateTiles(ctx, req)
	}
}

func (e Endpoints) CreateTiles(ctx context.Context, request *pb.CreateTilesRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("CreateTiles: nil request")
	}
	if e.CreateTilesEndpoint == nil {
		return nil, fmt.Errorf("CreateTiles: endpoint is not configured")
	}
	result, err := e.CreateTilesEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("CreateTiles: invalid response type %T", result)
	}
	return response, nil
}

func MakeCreateTilesEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateTilesRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateTiles: invalid request type %T", request)
		}
		return client.CreateTiles(ctx, req)
	}
}

func (e Endpoints) GetTile(ctx context.Context, request *pb.GetTileRequest) (*tilestream.Tile, error) {
	if request == nil {
		return nil, fmt.Errorf("GetTile: nil request")
	}
	if e.GetTileEndpoint == nil {
		return nil, fmt.Errorf("GetTile: endpoint is not configured")
	}
	result, err := e.GetTileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*tilestream.Tile)
	if !ok || response == nil {
		return nil, fmt.Errorf("GetTile: invalid response type %T", result)
	}
	return response, nil
}

func MakeGetTileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetTile: invalid request type %T", request)
		}
		return client.GetTile(ctx, req)
	}
}

func (e Endpoints) GetTileInfo(ctx context.Context, request *pb.GetTileInfoRequest) (*tilestream.TileInfo, error) {
	if request == nil {
		return nil, fmt.Errorf("GetTileInfo: nil request")
	}
	if e.GetTileInfoEndpoint == nil {
		return nil, fmt.Errorf("GetTileInfo: endpoint is not configured")
	}
	result, err := e.GetTileInfoEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*tilestream.TileInfo)
	if !ok || response == nil {
		return nil, fmt.Errorf("GetTileInfo: invalid response type %T", result)
	}
	return response, nil
}

func MakeGetTileInfoEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetTileInfoRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetTileInfo: invalid request type %T", request)
		}
		return client.GetTileInfo(ctx, req)
	}
}

func (e Endpoints) UpdateTile(ctx context.Context, request *pb.UpdateTileRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("UpdateTile: nil request")
	}
	if e.UpdateTileEndpoint == nil {
		return nil, fmt.Errorf("UpdateTile: endpoint is not configured")
	}
	result, err := e.UpdateTileEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("UpdateTile: invalid response type %T", result)
	}
	return response, nil
}

func MakeUpdateTileEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateTile: invalid request type %T", request)
		}
		return client.UpdateTile(ctx, req)
	}
}

func (e Endpoints) UpdateTileInfo(ctx context.Context, request *pb.UpdateTileInfoRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("UpdateTileInfo: nil request")
	}
	if e.UpdateTileInfoEndpoint == nil {
		return nil, fmt.Errorf("UpdateTileInfo: endpoint is not configured")
	}
	result, err := e.UpdateTileInfoEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("UpdateTileInfo: invalid response type %T", result)
	}
	return response, nil
}

func MakeUpdateTileInfoEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateTileInfoRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateTileInfo: invalid request type %T", request)
		}
		return client.UpdateTileInfo(ctx, req)
	}
}

func (e Endpoints) CreateLayer(ctx context.Context, request *pb.CreateLayerRequest) (*tilestream.Layer, error) {
	if request == nil {
		return nil, fmt.Errorf("CreateLayer: nil request")
	}
	if e.CreateLayerEndpoint == nil {
		return nil, fmt.Errorf("CreateLayer: endpoint is not configured")
	}
	result, err := e.CreateLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*tilestream.Layer)
	if !ok || response == nil {
		return nil, fmt.Errorf("CreateLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeCreateLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateLayer: invalid request type %T", request)
		}
		return client.CreateLayer(ctx, req)
	}
}

func (e Endpoints) BatchCreateLayer(ctx context.Context, request *pb.BatchCreateLayerRequest) (*pb.BatchCreateLayerResponse, error) {
	if request == nil {
		return nil, fmt.Errorf("BatchCreateLayer: nil request")
	}
	if e.BatchCreateLayerEndpoint == nil {
		return nil, fmt.Errorf("BatchCreateLayer: endpoint is not configured")
	}
	result, err := e.BatchCreateLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*pb.BatchCreateLayerResponse)
	if !ok || response == nil {
		return nil, fmt.Errorf("BatchCreateLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeBatchCreateLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchCreateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchCreateLayer: invalid request type %T", request)
		}
		return client.BatchCreateLayer(ctx, req)
	}
}

func (e Endpoints) UpdateLayer(ctx context.Context, request *pb.UpdateLayerRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("UpdateLayer: nil request")
	}
	if e.UpdateLayerEndpoint == nil {
		return nil, fmt.Errorf("UpdateLayer: endpoint is not configured")
	}
	result, err := e.UpdateLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("UpdateLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeUpdateLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateLayer: invalid request type %T", request)
		}
		return client.UpdateLayer(ctx, req)
	}
}

func (e Endpoints) BatchUpdateLayer(ctx context.Context, request *pb.BatchUpdateLayerRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("BatchUpdateLayer: nil request")
	}
	if e.BatchUpdateLayerEndpoint == nil {
		return nil, fmt.Errorf("BatchUpdateLayer: endpoint is not configured")
	}
	result, err := e.BatchUpdateLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("BatchUpdateLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeBatchUpdateLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchUpdateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchUpdateLayer: invalid request type %T", request)
		}
		return client.BatchUpdateLayer(ctx, req)
	}
}

func (e Endpoints) DeleteLayer(ctx context.Context, request *pb.DeleteLayerRequest) (*core.Null, error) {
	if request == nil {
		return nil, fmt.Errorf("DeleteLayer: nil request")
	}
	if e.DeleteLayerEndpoint == nil {
		return nil, fmt.Errorf("DeleteLayer: endpoint is not configured")
	}
	result, err := e.DeleteLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*core.Null)
	if !ok || response == nil {
		return nil, fmt.Errorf("DeleteLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeDeleteLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.DeleteLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("DeleteLayer: invalid request type %T", request)
		}
		return client.DeleteLayer(ctx, req)
	}
}

func (e Endpoints) GetLayer(ctx context.Context, request *pb.GetLayerRequest) (*tilestream.Layer, error) {
	if request == nil {
		return nil, fmt.Errorf("GetLayer: nil request")
	}
	if e.GetLayerEndpoint == nil {
		return nil, fmt.Errorf("GetLayer: endpoint is not configured")
	}
	result, err := e.GetLayerEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*tilestream.Layer)
	if !ok || response == nil {
		return nil, fmt.Errorf("GetLayer: invalid response type %T", result)
	}
	return response, nil
}

func MakeGetLayerEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetLayer: invalid request type %T", request)
		}
		return client.GetLayer(ctx, req)
	}
}

func (e Endpoints) BatchGetLayers(ctx context.Context, request *pb.BatchGetLayersRequest) (*pb.BatchGetLayersResponse, error) {
	if request == nil {
		return nil, fmt.Errorf("BatchGetLayers: nil request")
	}
	if e.BatchGetLayersEndpoint == nil {
		return nil, fmt.Errorf("BatchGetLayers: endpoint is not configured")
	}
	result, err := e.BatchGetLayersEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*pb.BatchGetLayersResponse)
	if !ok || response == nil {
		return nil, fmt.Errorf("BatchGetLayers: invalid response type %T", result)
	}
	return response, nil
}

func MakeBatchGetLayersEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchGetLayersRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchGetLayers: invalid request type %T", request)
		}
		return client.BatchGetLayers(ctx, req)
	}
}

func (e Endpoints) ListLayers(ctx context.Context, request *pb.ListLayersRequest) (*pb.ListLayersResponse, error) {
	if request == nil {
		return nil, fmt.Errorf("ListLayers: nil request")
	}
	if e.ListLayersEndpoint == nil {
		return nil, fmt.Errorf("ListLayers: endpoint is not configured")
	}
	result, err := e.ListLayersEndpoint(ctx, request)
	if err != nil {
		return nil, err
	}
	response, ok := result.(*pb.ListLayersResponse)
	if !ok || response == nil {
		return nil, fmt.Errorf("ListLayers: invalid response type %T", result)
	}
	return response, nil
}

func MakeListLayersEndpoint(client Client) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.ListLayersRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("ListLayers: invalid request type %T", request)
		}
		return client.ListLayers(ctx, req)
	}
}
