// Code generated by mojo. DO NOT EDIT.

package tilestream_client

import (
	"context"
	"fmt"

	core "github.com/mojo-lang/mojo/go/pkg/mojo/core"
	tilestream "github.com/ncraft-io/tilestream/go/pkg/tilestream"
	pb "github.com/ncraft-io/tilestream/go/pkg/tilestream/v1"
	"google.golang.org/grpc"
)

const FullServiceName = "tilestream.v1.Tilestream"

// NewGrpc wraps a caller-owned connection. It does not dial or close the connection.
func NewGrpc(conn grpc.ClientConnInterface, options ...ClientOption) (*Endpoints, error) {
	if conn == nil {
		return nil, fmt.Errorf("gRPC connection is nil")
	}
	config, err := newClientConfig(options)
	if err != nil {
		return nil, err
	}
	return newGrpc(conn, config), nil
}

func newGrpc(conn grpc.ClientConnInterface, config clientConfig) *Endpoints {
	remote := pb.NewTilestreamClient(conn)
	_ = remote
	_ = config
	endpoints := &Endpoints{}

	endpoints.CreateTileEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateTile: invalid request type %T", request)
		}
		var response *tilestream.Tile
		response, err := remote.CreateTile(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.BatchCreateTilesEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchCreateTilesRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchCreateTiles: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.BatchCreateTiles(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.CreateTilesEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateTilesRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateTiles: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.CreateTiles(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.GetTileEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetTile: invalid request type %T", request)
		}
		var response *tilestream.Tile
		response, err := remote.GetTile(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.GetTileInfoEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetTileInfoRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetTileInfo: invalid request type %T", request)
		}
		var response *tilestream.TileInfo
		response, err := remote.GetTileInfo(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.UpdateTileEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateTileRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateTile: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.UpdateTile(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.UpdateTileInfoEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateTileInfoRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateTileInfo: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.UpdateTileInfo(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.CreateLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.CreateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("CreateLayer: invalid request type %T", request)
		}
		var response *tilestream.Layer
		response, err := remote.CreateLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.BatchCreateLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchCreateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchCreateLayer: invalid request type %T", request)
		}
		var response *pb.BatchCreateLayerResponse
		response, err := remote.BatchCreateLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.UpdateLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.UpdateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("UpdateLayer: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.UpdateLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.BatchUpdateLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchUpdateLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchUpdateLayer: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.BatchUpdateLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.DeleteLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.DeleteLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("DeleteLayer: invalid request type %T", request)
		}
		var response *core.Null
		response, err := remote.DeleteLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.GetLayerEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.GetLayerRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("GetLayer: invalid request type %T", request)
		}
		var response *tilestream.Layer
		response, err := remote.GetLayer(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.BatchGetLayersEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.BatchGetLayersRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("BatchGetLayers: invalid request type %T", request)
		}
		var response *pb.BatchGetLayersResponse
		response, err := remote.BatchGetLayers(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	endpoints.ListLayersEndpoint = config.wrap(func(ctx context.Context, request interface{}) (interface{}, error) {
		req, ok := request.(*pb.ListLayersRequest)
		if !ok || req == nil {
			return nil, fmt.Errorf("ListLayers: invalid request type %T", request)
		}
		var response *pb.ListLayersResponse
		response, err := remote.ListLayers(config.grpcContext(ctx), req, config.grpcOptions...)
		if err != nil {
			return nil, err
		}
		return response, nil
	})

	return endpoints
}

var _ context.Context
